### ISSUE TITLE
meteor Npm.depends in external file

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#1008]
@Urigo I noticed that one of your meteor `package.js` files is structured like this:

```
var packagesJsonFile = path.resolve('./packages.json');
try {
  var fileContent = fs.readFileSync(packagesJsonFile);
  var packages = JSON.parse(fileContent.toString());
  Npm.depends(packages);
} catch (ex) {
  console.error('ERROR: packages.json parsing error [ ' + ex.message + ' ]');
}
```

Renovate currently cannot understand that. Is this a common design pattern that needs to be supported, or can those contents be moved back into `package.js`

**Comment by Urigo** [comment]
@rarkins I can't remember when it is, can you point me to that file on master?
can't find it...

**Comment by rarkins** [comment]
@Urigo it's a private repo with bank in its name. Path is store/packages/npm-container/package.js

**Comment by Urigo** [comment]
ohhh found it.
no you can close the issue, it's a local version of the `meteorhacks:npm` package which used to be the way to bring npm dependencies into Meteor before Meteor added the official supported.
