### ISSUE TITLE
Renovate not checking day of month in schedule

### ISSUE THREAD

**Issue by Siilwyn** [singapore/renovate#1047]
:wave: maybe I'm not understanding how it should work but renovate has opened multiple PRs this month like this: https://github.com/Siilwyn/css-declaration-sorter-atom/pull/58

In the PR it states the schedule is: "before 3am on the first day of the month", doesn't seem to follow this though.

Config:
```json
{
  "extends": ["config:semverAllMonthly"]
}
```

**Comment by rarkins** [comment]
Thank you for reporting the bug. The logs from this repo have helped me find that our existing "is this branch scheduled now?" algorithm *ignores* day of the month and is only checking day of the week and time of day. So your schedule basically becomes "before 3am". I'll fix!

**Comment by Siilwyn** [comment]
Cheers! Thanks for the timely response.

**Comment by rarkins** [comment]
Fixed. I'll push this live into the app today, so you hopefully shouldn't get any PR tomorrow "before 3am" 👍

**Comment by Siilwyn** [comment]
Awesome!
