### ISSUE TITLE
Digest updates need uniqueness

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#1050]
Existing digest updates are blocking future ones because title and branch name are the same. 

We should not recreateClosedPRs because there might be bad updates that users want to ignore. 

Suggest to add short hash to title

**Comment by ryansmith94** [comment]
Thanks for creating this @rarkins, just referencing my tweet here in case it's useful.

> @renovateapp Just got "Renovate Ignore Notification" for a merged PR, is that a bug? https://github.com/LearningLocker/xapi-service/pull/13#issuecomment-339817150

https://twitter.com/tweetRyanSmith/status/923918141939421184

**Comment by rarkins** [comment]
@ryansmith94 now fixed and new Dockerfile commit already made to your repo: https://github.com/LearningLocker/xapi-service/commit/b25b4a4394e58d13492718e771699563a03b2e50

Thanks for reporting the bug

**Comment by ryansmith94** [comment]
That's awesome! Thanks for quick fix @rarkins :smile: 

No worries.

**Comment by ryansmith94** [comment]
Hey @rarkins I've just seen this issue again https://github.com/LearningLocker/xapi-agents/pull/17#issuecomment-341690502

**Comment by rarkins** [comment]
@ryansmith94 thanks for bringing it to my attention. This time it looks like probably a *bug*:

![image](https://user-images.githubusercontent.com/6311784/32373993-36b8dcde-c09c-11e7-98d8-7eadd83ba551.png)

**Comment by rarkins** [comment]
I see a little more what's going on:
![image](https://user-images.githubusercontent.com/6311784/32374233-19eaa5d2-c09d-11e7-95c4-463778f8b14e.png)

The PR title got updated twice to match new digests, but the actual commit itself failed to update.

**Comment by rarkins** [comment]
@ryansmith94 this will be fixed shortly, however you will need to rename that existing PR yourself in order to get the digest updated. You can do that already though.

**Comment by ryansmith94** [comment]
Hey @rarkins, you're welcome for the report. Thanks for the quick fix and reply. Sorry for my slow reply, spent a lot of time pairing yesterday and must have missed this.

What do I need to change the PR title to? I'm guessing I just need to change the hash to be "48d5a6"?

**Comment by rarkins** [comment]
Change it in any way to fool the matching eg add a `-`

**Comment by ryansmith94** [comment]
Oh right nice will do, thanks @rarkins. Have a nice weekend 👍
