### ISSUE TITLE
Auto merged pushed a failing commit to master

### ISSUE THREAD

**Issue by ryansmith94** [singapore/renovate#1072]
Hey, just noticed that Renovate pushed a failing commit to our master branch and I don't think that's expected behaviour. Any idea how that might have happened?

The commit:
https://github.com/LearningLocker/xapi-statements/commit/2ca840343137f9960c0c839017be7d343bb0b3fa

The build:
https://travis-ci.org/LearningLocker/xapi-statements/builds/295683992

Here is our config:
```
{
  "extends": [":library"],
  "automerge": true,
  "automergeType": "branch-push",
  "major": {
    "automerge": false
  }
}
```

**Comment by ryansmith94** [comment]
Strangely the exact same update failed a build on another repository and Renovate created a PR over there (https://github.com/LearningLocker/launchr/pull/10) which is what I'd expect. That build actually failed because of a test that becomes flaky in Travis which is different to the other build.

**Comment by rarkins** [comment]
@ryansmith94 sorry for the inconvenience. Unfortunately I think GitHub has returned an incorrect "success" status for that branch.

An hour earlier:
```
{"repository":"LearningLocker/xapi-statements","level":20,"msg":"getBranchStatus(renovate/typescript-2.x)","time":"2017-10-31T17:29:55.625Z","v":0}
{"repository":"LearningLocker/xapi-statements","branch":"renovate/typescript-2.x","dependencies":["typescript"],"level":20,"msg":"Branch status is \"pending\" - skipping automerge","time":"2017-10-31T17:29:55.938Z","v":0}
```

then on the run where it automerged:
```
{"repository":"LearningLocker/xapi-statements","level":20,"msg":"getBranchStatus(renovate/typescript-2.x)","time":"2017-10-31T18:25:41.026Z","v":0}
{"repository":"LearningLocker/xapi-statements","branch":"renovate/typescript-2.x","dependencies":["typescript"],"level":30,"msg":"Automerging branch","time":"2017-10-31T18:25:41.154Z","v":0}
```

The logic in Renovate seems too simple for there to be a bug there. If `res.body.status === 'success'` then.. we automerge.

We are utilising GitHub's "combined" status as documented here: https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref

What I'll do is add some debug code for all status checks so we can see exactly what is returned if this happens again.

**Comment by ryansmith94** [comment]
Hey @rarkins, no worries, the project is actually a dependency of a larger service for us and it hasn't been updated there yet so it's not gone live and I don't think that failing test would have caused an issue for anyone.

Ok that's a bit odd. I'll have a bit of a dig and follow up with them if needed (I'll link here to any conversation with them). Thanks for taking the time to investigate and providing logs, code, and docs.

Ok that sounds great thanks @rarkins! 👍 I'll close this for now and post in here again if the issue reoccurs.

**Comment by rarkins** [comment]
@ryansmith94 please reopen this if you experience it again. I'm in the process of adding debugging to log both the GitHub API branch `state` value (which we use), and the `statuses` array (which we ignore, because GitHub is meant to summarise that into a single value for `state`), so that any future automerge - whether mistaken or not - should be preceded by a log of what GitHub sends us. So if it happens again and you can alert me quickly again like this time (I purge debug logs usually after 3-4 days) then we should have a good idea of who's at fault.

**Comment by rarkins** [comment]
The options I can think of are:

1. Travis temporarily/incorrectly set status to success, which GitHub passed on to us
2. GitHub calculated a wrong "state" value for us (success when it should have been pending or failed)
3. There's a bug in my few lines of code that I can't spot

**Comment by ryansmith94** [comment]
I will do, thanks @rarkins 👍 Ok that sounds good, I'll let you know as soon as I can, thanks for that.

Yeah those options seem reasonable. I'm just writing an email to Github support now, strangely I couldn't find a Github issues for Github issues 😆

**Comment by rarkins** [comment]
@ryansmith94 yeah, GitHub don't eat their own dogfood in that sense. For GitHub Apps, instead of a repository to file issues, they use a "forum". Because of the volume of API requests that the App generates each day I see a lot of random errors from GitHub but have no idea where to file them if I was inclined to do so. Also FYI I think they probably can't track down anything unless you/I were to save actual request IDs from API response headers.

**Comment by ryansmith94** [comment]
Yeah haha. Ah right that sounds like a pain. Yeah that's a good point, I've sent them an email anyway, I guess I can just see how they respond and go from there. I've pasted the email below for reference.

> Hey, we're using a tool called Renovate to automatically merge updates to our dependencies. Last night Renovate automatically merged an update into our master branch that failed a build, but in those cases Renovate should create a pull request for the update instead to invoke some human attention.
> 
> I've reported this issue to Renovate (singapore/renovate#1072), however, they think the issue might have been caused by an incorrect status response from Github's APIs. I'm wondering if you'd be able to respond to that issue in order to provide some more details. It's also possible that Travis is incorrectly providing the status of builds or that we have a flaky test that just happened to pass once and never again.

**Comment by ryansmith94** [comment]
I think it's unlikely that the failing test is flaky since it's not passed a single time since being pushed into the master branch.

**Comment by ryansmith94** [comment]
Just had a response from them:

> Hi Ryan,
> 
> Thanks for reaching out. I'm not sure I understand the situation from reading that issue, and what exactly seems to be the problem that's being described. In addition, commenting on issues like that isn't how we normally provide support.
> 
> Could you ask the people who believe there was a problem on our end with the API to use https://github.com/contact and describe the problem as clearly and in as many details as possible ? That should help us investigate and offer advice.
> 
> Thanks,
> Ivan

**Comment by ryansmith94** [comment]
My response to them:

> Ok, so the issue appears to be that the Github Statuses API potentially incorrectly returned the "state" property with the "success" value when it should have returned a different value. I'm guessing this might have happened if Travis CI didn't pick up the commit immediately.
> 
> I've copied your message into the Github issue, so they may contact you separately.
