### ISSUE TITLE
Renovate v10 stability

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#1075]
Renovate v10 has been merged to master and released as v10.0.0 to npm, however it is tagged as `next` and not `latest`. Please subscribe to this issue to be notified of progress towards getting it tagged as `latest`.

**Comment by rarkins** [comment]
Renovate v10 is now considered stable for GitHub - it is running on the GitHub App across 1000+ projects without any additional errors or warnings caused. I would prefer that some active GitLab users can test the new v4-only API first before I tag v10 as `next`, but I also don't want to wait forever. Please speak up if you are able to offer any feedback in the next week.

**Comment by hbetts** [comment]
I just switched my private `renovate-job` on GitLab, replacing `yarn global add renovate@latest` with `yarn global add renovate@10.5.5`.

I didn't check to see if I needed to upgrade Node from 6 to 8 so I received the typical compatibility error:

```bash
error renovate@10.5.5: The engine "node" is incompatible with this module. Expected version ">=8".
error Found incompatible module
```

Once I resolved that issue, `renovate` installed successfully and began to run on my projects:

However, I'm now receiving generic 400 errors from GitLab:

```bash
INFO: Branch needs creating (repository=hyper-expanse/semantic-release-github, dependencies=tmp, branch=renovate/tmp-0.x)
 WARN: Could not find globally installed yarn (repository=hyper-expanse/semantic-release-github, dependencies=tmp, branch=renovate/tmp-0.x)
 INFO: Generated lockfile (repository=hyper-expanse/semantic-release-github, dependencies=tmp, branch=renovate/tmp-0.x)
       "seconds": 8,
       "type": "yarn.lock",
       "stdout": "yarn install v1.2.1\n[1/4] Resolving packages...\n[2/4] Fetching packages...\n[3/4] Linking dependencies...\n[4/4] Building fresh packages...\nsuccess Saved lockfile.\nDone in 7.43s.\n",
       "stderr": "warning Ignored scripts due to flag.\n"
ERROR: Error updating branch: undefined (400) (repository=hyper-expanse/semantic-release-github, dependencies=tmp, branch=renovate/tmp-0.x)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.com",
         "hostname": "gitlab.com",
         "method": "POST",
         "path": "/api/v4/projects/hyper-expanse%2Fsemantic-release-github/repository/branches",
         "protocol": "https:",
         "url": "https://gitlab.com/api/v4/projects/hyper-expanse%2Fsemantic-release-github/repository/branches",
         "statusCode": 400,
         "statusMessage": "Bad Request",
         "headers": {
           "server": "nginx",
           "date": "Wed, 08 Nov 2017 16:33:46 GMT",
           "content-type": "application/json",
           "content-length": "26",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "905befdb-7a82-455a-818e-4c9fb7d14d28",
           "x-runtime": "0.080713",
           "ratelimit-limit": "600",
           "ratelimit-observed": "26",
           "ratelimit-remaining": "574"
         }
       }
 INFO: Finished repository (repository=hyper-expanse/semantic-release-github)
```

I've increased the log level, and I'll post what I can once that job runs.

**Comment by hbetts** [comment]
Here's a little more output for a different package with _DEBUG_ messages:

```bash
 INFO: Generated lockfile (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
       "seconds": 9,
       "type": "yarn.lock",
       "stdout": "yarn install v1.2.1\n[1/4] Resolving packages...\n[2/4] Fetching packages...\n[3/4] Linking dependencies...\n[4/4] Building fresh packages...\nDone in 7.92s.\n",
       "stderr": "warning Ignored scripts due to flag.\n"
DEBUG: yarn.lock hasn't changed (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
DEBUG: No updated lock files in branch (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
DEBUG: 1 file(s) to commit (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
DEBUG: commitFilesToBranch('renovate/gl-got-8.x', files, message, 'master)' (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
DEBUG: Checking if branch exists: renovate/gl-got-8.x (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
DEBUG: Branch doesn't exist (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
DEBUG: Creating branch renovate/gl-got-8.x (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
ERROR: Error updating branch: undefined (400) (repository=hyper-expanse/conventional-gitlab-releaser, dependencies=gl-got, branch=renovate/gl-got-8.x)
```

The most I can get out of it is that perhaps the wrong arguments are being provided to the GitLab _branch_ API endpoint.

Let me take a look at what those arguments should be.

**Comment by rarkins** [comment]
@hbetts seems to me:
1. Branch does exist
2. Our branchExists() returns false
3. When we try to *create* the branch, you get the failure

The "Error updating branch" log is just a badly or unfortunately worded error message, I think it's actually creating it, not updating it.

**Comment by rarkins** [comment]
Our code:
```
async function branchExists(branchName) {
  logger.debug(`Checking if branch exists: ${branchName}`);
  try {
    const url = `projects/${
      config.repoName
    }/repository/branches/${branchName.replace('/', '%2F')}`;
    const res = await get(url);
    if (res.statusCode === 200) {
      logger.debug('Branch exists');
      return true;
    }
    // This probably shouldn't happen
    logger.debug("Branch doesn't exist");
    return false;
  } catch (error) {
    if (error.statusCode === 404) {
      // If file not found, then return false
      logger.debug("Branch doesn't exist");
      return false;
    }
    // Propagate if it's any other error
    throw error;
  }
}
```

Here's the relevant GitLab doc:
![image](https://user-images.githubusercontent.com/6311784/32609102-bdcd6a34-c55e-11e7-84aa-cba2e4dc9a43.png)

Note it explicitly says URL-encoded for project but not for branch. It seems this might be a case where we *shouldn't* url encode the branch. I will look into this, thanks for your help so far.

**Comment by rarkins** [comment]
And yet in the API intro GitLab says you must url-encode branch: https://docs.gitlab.com/ee/api/README.html#branches-amp-tags-name-encoding

I will raise a separate issue for this to get to the bottom of it

**Comment by hbetts** [comment]
I'm running `renovate` locally now, and I get the following error for `semantic-release-gitlab`:

```bash
DEBUG: Branch doesn't exist (repository=hyper-expanse/semantic-release-gitlab, dependencies=codecov, branch=renovate/codecov-3.x)
DEBUG: Creating branch renovate/codecov-3.x (repository=hyper-expanse/semantic-release-gitlab, dependencies=codecov, branch=renovate/codecov-3.x)
ERROR: Error updating branch: undefined (400) (repository=hyper-expanse/semantic-release-gitlab, dependencies=codecov, branch=renovate/codecov-3.x)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.com",
         "hostname": "gitlab.com",
         "method": "POST",
         "path": "/api/v4/projects/hyper-expanse%2Fsemantic-release-gitlab/repository/branches",
         "protocol": "https:",
         "url": "https://gitlab.com/api/v4/projects/hyper-expanse%2Fsemantic-release-gitlab/repository/branches",
         "statusCode": 400,
         "statusMessage": "Bad Request",
         "headers": {
           "server": "nginx",
           "date": "Thu, 09 Nov 2017 14:10:25 GMT",
           "content-type": "application/json",
           "content-length": "26",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-content-type-options": "nosniff",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "3b75437f-32de-41e5-98cd-89035c9fd815",
           "x-runtime": "0.062609",
           "ratelimit-limit": "600",
           "ratelimit-observed": "222",
           "ratelimit-remaining": "378"
         }
       }
```

However there are no branches in that project other than `master`:

![branches](https://user-images.githubusercontent.com/6701030/32609746-491c433c-c526-11e7-8dd9-510b87bd1701.png)

**Comment by hbetts** [comment]
Oh... I think I figured it out. There is what appears to be a typo for `baseBranch`:

```javascript
body: {
          branch: branchName,
          ref: config.basBranch,
        },
```

**Comment by rarkins** [comment]
@hbetts thank you for spotting that! fix on the way

**Comment by hbetts** [comment]
Awesome!

Renovate hasn't finished running yet, but I can confirm that it's creating branches once again (and filing merge requests)

**Comment by rarkins** [comment]
@hbetts released in renovate@v10.6.2

**Comment by hbetts** [comment]
Running v10.6.2 now, and everything looks great! I also noticed labels on GitLab work again. Probably because of your work in #1064.

For what it's worth Ship It! :+1:

**Comment by rarkins** [comment]
I want to check also that assignees is working too (because of id/ iid concerns). Can you confirm if you are using them at time of PR creation?

**Comment by hbetts** [comment]
I haven't using the `assignee` feature.

I just pushed that feature to one of my project - https://gitlab.com/hyper-expanse/npm-publish-git-tag/commit/9f96a5be29dced9152b261906081e324dd2aea05

However, it doesn't appear to assign the merge request to me - https://gitlab.com/hyper-expanse/npm-publish-git-tag/merge_requests/30

I'll start looking into it later.

**Comment by rarkins** [comment]
I've concluded that `assignees` is not working in GitLab and either never has been, or has been broken for some time - it's not a result of Renovate v10. I have opened #1131 to track this and do not consider it a blocker for shipping Renovate v10.

**Comment by rarkins** [comment]
I fixed the `assignees` problem now. I think I'll wait until Monday before marking v10 as latest.

**Comment by hbetts** [comment]
> FYI it won't assign after any PR is already created

Yep. That is one reason testing `renovate` is taking me so long. I go through the process of deleting merge requests and branches to ensure a clean project environment for Renovate to renovate.

> I've concluded that assignees is not working in GitLab and either never has been, or has been broken for some time

It worked when I first started using `renovate`, but stopped working several months ago.

> I fixed the assignees problem now. 

That's great!
