### ISSUE TITLE
Renovate crashes on repos with empty git URLs

### ISSUE THREAD

**Issue by fgnass** [singapore/renovate#1109]
Some non-open-source npm packages like https://www.npmjs.com/package/bitmovin-player contain repository fields with empty URLs. This causes renovate to crash with the following error:

```
/var/lib/jenkins/.npm/_npx/16425/lib/node_modules/renovate/node_modules/changelog/lib/datasrc/npm.js:24
                    repo = repoTree.url;
                                   ^

TypeError: Cannot read property 'url' of undefined
```

I submitted a PR to changelog that fixes the underlying issue: https://github.com/dylang/changelog/pull/48

**Comment by rarkins** [comment]
@fgnass thanks for the heads-up and fix. I have published a new patch of `changelog` and `renovate` will get the update soon.
