### ISSUE TITLE
Contributing with a windows environment

### ISSUE THREAD

**Issue by jycouet** [singapore/renovate#1148]
Hi,

Few points to enhance to be able to have some contibutor with windows environment :)
- [x] package.json
    - [x] setting environment variables (may be we should use [cross-env](https://www.npmjs.com/package/cross-env) as you suggested)
    - [x] `"prettier": "prettier '**/*.{js,json}' --write"` should become `"prettier": "prettier \"**/*.{js,json}\" --write"` but I don't know if it's working on other os than windows
- [x] Tests (5 are failing)
    - [x] path.join issue: `a\\test.json` and `a/test.json` in snapshots

This issue is more like a reminder :)

**Comment by rarkins** [comment]
If anyone runs Windows regularly and would like to contribute, please go ahead!
