### ISSUE TITLE
yarn error "Invalid string length" (VSTS)

### ISSUE THREAD

**Issue by jycouet** [singapore/renovate#1158]
Hello, 
I get this message quite often (just after a `INFO: yarn install error`)
![image](https://user-images.githubusercontent.com/5312607/32701271-aa981a92-c7d2-11e7-9d38-b76241a85c58.png)

Do you have an idea of where to investigate?

Thank you

**Comment by rarkins** [comment]
I've never seen an "invalid string length" yarn error before sorry

**Comment by jycouet** [comment]
I just found out!!!
It's due to the getFile content in VSTS, I was not getting the full file! Just the first part... so on my tests prj it was working fine. But now on bigger project, I have the issue!

I'm correcting it right now
