### ISSUE TITLE
Renovate not using config file

### ISSUE THREAD

**Issue by p3k** [singapore/renovate#1181]
I have successfully run `renovate` with a lot of CLI options and got the MR and branch for configuration / onboarding.

However, when I try to use the same settings in a config file (tried `config.js` as well as `renovate.json`) I always get errors that lead me to think the configuration files are ignored.

```
# cat renovate.json
{
  "extends": [
    "config:base",
    ":preserveSemverRanges"
  ],
  "platform": "gitlab",
  "endpoint": "https://gitlab.my.domain/api/v4",
  "repositories": ["my/repo"],
  "ignorePaths": [
    "**/node_modules/**", 
    "**/bower_components/**"
  ]
}

# renovate --token $my_token
 WARN: No repositories found - did you want to run with flag --autodiscover?
 INFO: Renovate finished

# renovate --token $my_token my/repo
 INFO: Renovating repository (repository=my/repo)
 INFO: Retrying request (repository=my/repo)
       "statusCode": 401,
       "message": "Bad credentials (401)"
       …

# renovate --token $my_token --platform gitlab --endpoint https://gitlab.my.domain/api/v4 --pin-versions false --ignore-paths **/bower_components/**,**/node_modules/** my/repo
```

The last command finally does the renovation but it already comes with all of the settings in the config file except the `config:base` extension, anyway – so what is the config file good for? 

Moreover, the proposed `renovate.json` by the MR in the repo does not change either, nor does it reflect the settings from the CLI…

What am I doing wrong?

**Comment by rarkins** [comment]
`renovate.json` is used only for within the repository although I suppose we could add support for it on the client too. Instead it should be a `config.js` which exports its settings. If you find Renovate is not detecting it then can you try `RENOVATE_CONFIG_FILE=/absolute/path/config.js renovate`?

FYI the onboarding will ways suggest a renovate.json regardless of what features you have in your client config. You can either skip onboarding or close the onboarding MR unmerged if you wish.

**Comment by p3k** [comment]
Yes, the latter works:

```
# export RENOVATE_CONFIG_FILE=/home/tobi/path/to/config.js
# renovate --token $my_token
…
```

I think it is quite important to be sure the config file is working as expected, so maybe you could in fact consider to make this work on the client-side. Or at least it could be communicated more clearly which config is reflected where…

Anyway, thanks for the quick help!
:smile_cat:

**Comment by p3k** [comment]
Is it correct that the `renovate.json` needs to be at the root-level of the default branch (e.g. master or develop) of the remote?

**Comment by rarkins** [comment]
Yes, renovate.json needs to be present in the default branch at the root. 

You can test the validity of the renovate.json in any onboarding PR. After you rerun Renovate it will update the results and also display any warnings or errors in the config
