### ISSUE TITLE
Support for other package managers?

### ISSUE THREAD

**Issue by khornberg** [singapore/renovate#121]
I really like what I see in this repo and I think it is great work. 
I would like to have this same work flow but for different package managers as well. 

Do you think it would be a good fit to abstract the package manager (npm/yarn, package.json) to allow for others?

**Comment by rarkins** [comment]
Code- wise it should be fairly easy to fit in. 
The challenge might be how to keep the config elegant!
Any particular ones you had in mind already that can be scoped?

**Comment by khornberg** [comment]
My initial thought are python packages since that is something I use daily.

I have to think about the config

**Comment by hbetts** [comment]
The company I work for may be interested in using a tool like `renovate` to support the same merge/pull request upgrade workflow for Python projects as well (There are other languages, such as Go, Java, and .NET that are in heavy use too).

Once I get some free time after #139, I may circle around again to see whether y'all ( @khornberg & @rarkins ) are still interested in moving forward with non-JavaScript languages.

**Comment by rarkins** [comment]
I've added separate issues for each language: #931 (Python), #932 (Ruby), #933 (Go), #934 (Java) and #935 (.NET), so now closing this issue.
