### ISSUE TITLE
Support recreating unmergeable branches in GitLab

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#132]
GitLab doesn't support low-level git API like GitHub, so currently we mark every PR as `canRebase=false`. But it would perhaps be desirable to close existing PR and create a replacement, instead of leaving the existing one as conflicted.

Cc @guumaster

**Comment by guumaster** [comment]
Depends on your GitLab version, ut turns out that [Gitlab EE](https://docs.gitlab.com/ee/workflow/rebase_before_merge.html#rebase-before-merge) has the feature, but its not exposed through the API.

**Comment by rarkins** [comment]
In that case I guess we can't use it though? BTW I have been testing against the public gitlab.com myself

**Comment by hbetts** [comment]
The public GitLab.com site is their Enterprise Edition.

For what it's worth, I would lean on the side of not using any specific EE features as there are a lot of non-profits out there using GitLab Community Edition, and they too may benefit from `renovate`.

**Comment by Autre31415** [comment]
With npm5 out and package-locks being a default feature this issue has become a whole lot more relevant.

So far my workflow to handle this manually has been to nuke the conflicting branch and re-run renovate to generate a new branch and continue using the same PR. This is not perfect however as we lose an updated description and title in the case of newer versions of deps being added during this process. If we can overcome that drawback the branch nuking may be a viable solution though.

What do you guys think?

**Comment by rarkins** [comment]
> we lose an updated description and title in the case of newer versions of deps being added during this process.

Could you give an example of this so I understand?

**Comment by Autre31415** [comment]
It would be a bit challenging to stage the scenario myself. But the steps to reproduce this naturally would be:
1. Having a fairly stale PR waiting in the queue that has a merge conflict (Usually due to package-lock now)
2. Deleting the source branch (Without deleting the PR)
3. Running renovate, which will detect the out-of-date dep and go ahead and make the branch again.
4. The PR is now live again, and if there just so happened to be a newer version of the dep than the PR reflected renovate would have committed to that version, but the title and description of the PR will not reflect this, only the latest commit message will.

**Comment by rarkins** [comment]
@Autre31415 Are you saying that in GitLab you can delete a branch and it does not automatically delete/close the MR? 

If so then this behaviour differs from GitHub but that would be a *good* thing and help me solve the problem.

**Comment by Autre31415** [comment]
That is correct, and that has been my manual solution to dealing with this problem, with the only drawback being that the title and description will not update if the dependency has a newer version when the branch is remade.

**Comment by rarkins** [comment]
That's quite possibly the trick we need then. 

So:

1. We have a conflicting branch/MR
2. We delete the branch. "Zombie" MR stays open!?
3. We recreate the branch, based off of master - no conflicts
4. GitLab "reconnects" the zombie MR with its recreated branch?
5. Renovate needs to detect the MR and update its title/description

The strange thing is that (5) is meant to be the way things work already. If you're sure it's not - or was it just theoretical - then hopefully it can be fixed. FYI: renovate will check the MR title and description on every iteration and update it if the old one is outdated.

**Comment by Autre31415** [comment]
I can confirm through my own use of renovate that 2 and 4 are the case, with 5 being the only problem. I've been dealing with this problem since npm5 dropped and package-lock created merge conflicts galore.

**Comment by rarkins** [comment]
Thanks for the info. I think it can be fixed and the end result will hopefully be as elegant as the existing GitHub rebasing.

**Comment by rarkins** [comment]
I'm looking into this now. I think an easy way to reproduce such a challenge in an empty repo is:

1. Install a version of dependency 2 versions old (e.g. `eslint@3.0`)
2. Run renovate (will create 2 MRs, one for each major version)
3. Merge the 3.x branch
4. The 4.x will now be in conflict

**Comment by rarkins** [comment]
Confirming how it looks to me when I delete the branch:

![image](https://user-images.githubusercontent.com/6311784/27425262-2476f646-5738-11e7-841c-01942a929501.png)

**Comment by rarkins** [comment]
Nearly done. You get a bit of "noise" in the "Discussion" area but otherwise it's quite elegant:

![image](https://user-images.githubusercontent.com/6311784/27425808-eb8a8c4c-5739-11e7-8a41-e8ee4dfae74a.png)

**Comment by rarkins** [comment]
@Autre31415 please try renovate version `8.38.0` and let me know how it goes. It should automatically delete and recreate any branches that have got into unmergeable state (e.g. due to `package-lock.json`.

BTW in case you have "related" packages causing this problem (e.g. `eslint` and friends), consider having a package "group" to put them all into the same branch and avoid the merge/rebase/merge/rebase cycle when multiple are released at similar times.

**Comment by Autre31415** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 

I just tried it out and am happy to report that our merge conflicts are being handled properly now, and with updated descriptions. Awesome work!

**Comment by rarkins** [comment]
Great news! Thanks for tip re: how GitLab let's you delete branches without automatically closing the MR - that was the whole reason why I couldn't do the same thing on GitHub and assumed the same for GitLab.

**Comment by hbetts** [comment]
Also wanted to chime in and say what an awesome enhancement!

The extra discussion updates are a minor matter given the enormous benefit.
