### ISSUE TITLE
Update all projects for a user

### ISSUE THREAD

**Issue by destroyerofbuilds** [singapore/renovate#146]
Instead of passing a single project, such as `singapore/renovate`, I would like to pass just the group, like `singapore`, and expect `renovate` to submit the appropriate merge requests against each project within the group.

**Comment by rarkins** [comment]
In the scenario you have in mind, would the configured token be owned by `singapore`? In that case even the "group" would be implicit. I was thinking about this already but not sure whether to make it the default behaviour or not, if no repositories are provided.

**Comment by destroyerofbuilds** [comment]
> In the scenario you have in mind, would the configured token be owned by singapore?

In my current `renovate` use, I have a dedicated _bot_ account, and use the bot's token to submit merge requests against each project I individually list. (The bot is just a dedicate user I created on GitLab and is listed as a [Developer](https://docs.gitlab.com/ee/user/permissions.html) under that group. It's actually listed as a _Developer_ under two groups.)
