### ISSUE TITLE
CLI Configuration Option Restrictions

### ISSUE THREAD

**Issue by destroyerofbuilds** [singapore/renovate#190]
Could CLI configuration restrictions be lifted for those options that are set to `cli: false` in https://github.com/singapore/renovate/blob/e844388e48efd5a53b4cc9c0f8040d81dc3b0606/lib/config/definitions.js

As mentioned [here](https://github.com/singapore/renovate/pull/105#pullrequestreview-32749596), I would really like to set a default yarn maintenance message for all my projects that are maintained by a single `renovate` instance.

**Comment by rarkins** [comment]
@destroyerofbuilds is there any major downside if you specify it by environment variable instead?

I'm trying to recall all the reasons I had for disabling templates via CLI. I'm trying to recall if it was just to stop polluting the CLI help command!

**Comment by rarkins** [comment]
You can currently also specify it via a config file in any location of your choosing (`./config.js` by default).

**Comment by destroyerofbuilds** [comment]
> @destroyerofbuilds is there any major downside if you specify it by environment variable instead?

`env` is set to `false` as well. (though I haven't actually tried to see if that option works the way I assume it does)

The only _downside_ to using an environment variable would just be that I would have `ENVIRONMENT_VARIABLE=SOMETHING` followed by `renovate` followed by `--FLAG`. So it doesn't really reduce the complexity of the call to `renovate`, just the location of the configuration in the call to `renovate`.

> I'm trying to recall all the reasons I had for disabling templates via CLI.

If you happen to remember, is that something we could add to the [design document](https://github.com/singapore/renovate/blob/master/docs/design-decisions.md)?

> You can currently also specify it via a config file in any location of your choosing (./config.js by default).

I hadn't though to try that. I have an empty Jenkins job that just `yarn` installs `renovate` locally, and then calls `renovate` with various CLI flags. I thought config files were only usable within the projects that were fetched by `renovate`.

**Comment by rarkins** [comment]
> If you happen to remember, is that something we could add to the design document?

Yes, good idea. That doc is surprisingly hard to keep updated :)

> I thought config files were only usable within the projects that were fetched by renovate.

No, it's actually like this:

Configuration is supported via any or all of the below:
- Configuration file
- Environment
- CLI
- `renovate.json` in target repository
- `renovate` field of `package.json` in target repository

Check out https://github.com/singapore/renovate/blob/master/docs/configuration.md#configuration-file in case it helps you in the meantime.

**Comment by rarkins** [comment]
@destroyerofbuilds please use the corresponding environment variable via CLI, or consider the `config.js` option instead.

renovate 8.21.5 published 🎉
