### ISSUE TITLE
yarnMaintenanceCommitMessage does not appear to do anything

### ISSUE THREAD

**Issue by daprahamian** [singapore/renovate#205]
I've confirmed that the value of `yarnMaintenanceCommitMessage` is what I want in the config.

However, the actual commit posted by `renovate` uses `commitMessage`.

Looking through the source code, it doesn't appear that `yarnMaintenanceCommitMessage` is used anywhere.

**Comment by rarkins** [comment]
> However, the actual commit posted by renovate uses commitMessage.

What exact commit message are you seeing? Is it `'Update dependency  to version '` ?

**Comment by rarkins** [comment]
I've pushed what I think is the fix to version 8.21.9 - please test it out

**Comment by daprahamian** [comment]
I will test this out later today.
