### ISSUE TITLE
Getting 'Response code 400' when trying to connect to repo in self-hosted gitlab server

### ISSUE THREAD

**Issue by Autre31415** [singapore/renovate#218]
I've been working on deploying renovate to manage dependencies on my own personal gitlab server and I have hit a wall.

I started with a repo which I know has some out of date dependencies to test the functionality. I created an account in gitlab to use as a bot, gave it Developer powers over the repo and created the api key. I then ran the renovate command passing the `token <token>`, `platform gitlab`, `endpoint http://path/to/gitlab/api` args, and it seemed to work.

So moving on from the test repo I attempted to deploy it on a repo that was contained within a group. I gave my bot Developer powers in that group (And by extension the repo itself) and attempted this same process, but with hit with a `Response code 400 (Bad request)` error, with no other information. I tried setting the log level to verbose but that only dumped the config and not more info about my error. I messed around with the permissions of the bot, created a new access token, removed the bot from the group and gave it Developer access to only the one repo, and even tried a different account altogether all to no avail.

My theory was there was an issue with repos in groups, so to test this I moved my original repo that worked into a group of its own and tested it, and viola a 400 error. But things became more confusing when I moved it out of the group and back to the user and the 400 error persisted.

It seems like a possible bug here, but it's also quite possible I might be missing something?

**Comment by rarkins** [comment]
I assume it's Gitlab returning the 400? And I wonder if that's because of permission problem with the token. Perhaps we can confirm elsewhere if 400 is their usual response to permissions problems. 

If both of those are true then I'm not sure if there's anything on renovate side that could change, unless we're using their API wrong somehow.

**Comment by Autre31415** [comment]
I passed a wrong token on purpose to test just that and I would get a 404 response instead in that case. According to some skimming of the gitlab API docs a 400 is returned when there is an issue with the request sent to the API, which is pretty vague

**Comment by rarkins** [comment]
Can you confirm if the 400 is failing for the very first API request in the renovate flow?

Also is there any way to test with a completely separate repo/group/account so that we can confirm this affects all gitlab instances and not somehow just your setup? eg any way to simulate with the public gitlab.com instance?

We shouldn't also check that "developer" group access definitely gives API permissions

**Comment by Autre31415** [comment]
I'm going to work on replicating this on the public gitlab service. In theory there should really be no difference between a personal server with default configuration and the public one.

**Comment by Autre31415** [comment]
I've done a whole ton of digging and I've gotten to the bottom of the issue. I was pointing to v4 of the api on my server, while renovate was designed with the v3 API in mind (And points automatically to v3 of the gitlab API with no endpoint specified).

The v4 API is a fairly recent addition, coming standard with any installation of gitlab 9.0+ and fortunately v3 is still supported out of the box.

In light of this I suggest simply mentioning this in the config docs under endpoint that v3 is needed and v4 is not yet supported.

**Comment by rarkins** [comment]
Thank you @Autre31415 

I have raised issue #220 for (future) implementation of v4 API support, and for now I have updated the `readme.md` to noted in two different places about the need for API v3.
