### ISSUE TITLE
Support npm 5

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#222]
http://blog.npmjs.org/post/161081169345/v500

**Comment by steebchen** [comment]
This would be awesome, especially since yarn is not really needed anymore in my opinion. And it ships with node v8, so people will automatically have the npm lockfile in their repos.

**Comment by hbetts** [comment]
@steebchen, what enhancements to `renovate` are needed to support npm@5?

**Comment by steebchen** [comment]
It's quite similar to yarn: npm creates a lockfile called `package-lock.json` and this lockfile is updated every time you npm i or rm something. -S/--save also does not exist anymore.

**Comment by rarkins** [comment]
I think this is pretty easy, because it needs the identical behaviour we already have for `yarn`. If a `package-lock.json` file exists then run `npm install` and see if the `package-lock.json` file changes. See #224

**Comment by rarkins** [comment]
renovate 8.22.0 published 🎉
