### ISSUE TITLE
Performance: Cache Registry Requests

### ISSUE THREAD

**Issue by hbetts** [singapore/renovate#246]
`renovate` makes one registry request per dependency, per package, that it's _renovating_.

There are several projects that follow the monorepo approach ([conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) being a good example), where the packages within the monorepo share a large number of common dependencies.

One possible enhancement would be to cache registry metadata requests and remove them from the cache after some specified TTL.

**Comment by rarkins** [comment]
Npm seem to have a 5 minute cache time on requests so perhaps we simply follow that suggested ttl.

The question then is:
- what storage structure (in mem or disk)
- how to prune/expire locally (proactively or reactively)

Memory-only storage presents a risk of using too much, although by definition the max Mem use would only need to be equal to the amount of npm answers we can cache within 5 minutes. 

Also need to make sure not to expose (or perhaps cache at all) private answers across repos.

**Comment by rarkins** [comment]
I guess the simplest implementation to begin with would be public-only, memory-only caches complying to npm's suggested expiry.

**Comment by rarkins** [comment]
Idea: aggressively prune non responses before caching. In that case in-memory shouldn't be an issue
