### ISSUE TITLE
Performance: by-field End-point

### ISSUE THREAD

**Issue by hbetts** [singapore/renovate#247]
Npm once had a `by-field` end-point that allowed you to retrieve just the metadata field you want for a package.

More background information on how `package-json` package tried to leverage that API end-point before it was removed can be found in sindresorhus/package-json/issues/9

I've requested that the API end-point be added back here - npm/registry/issues/93

If we can encourage npm to add back the API end-point, we can just request the `versions` field instead of fetching all of a package's metadata.

**Comment by rarkins** [comment]
Closing, as this is impossible without changes from npm.
