### ISSUE TITLE
Semantic commit support

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#303]
This issue is to discuss/implement what enhancements are needed to `renovate` to conveniently support projects that use semantic commit messages.

Some questions:

1. How many different semantic commit "types" are commonly used?
   * [Sparkbox's original suggestion](https://seesparkbox.com/foundry/semantic_commit_messages)
   * [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.uyo6cb12dt6w)
2. What's the appropriate commit type for renovate upgrades and should it differ based on patch/minor/major?

**Comment by rarkins** [comment]
Cc @hbetts @destroyerofbuilds - would appreciate your feedback here

**Comment by rarkins** [comment]
Here's an example commit from `angular/angular`: https://github.com/angular/angular/commit/065b76d14c0bf3bc89625ca492c1d7d153dfc51b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

It's upgrading a patch version and uses this message: `feat(core): upgrade dep on zone.js to 0.8.9`

**Comment by rarkins** [comment]
`angular-cli` is another example. Here's the commit history for their `package.json`: https://github.com/angular/angular-cli/commits/master/package.json

When dependency upgrades are done in isolation, they're usually labeled as type `feat`. However I also see times when a commit labeled as a refactor changes major versions of dependencies, e.g. https://github.com/angular/angular-cli/commit/4563ec583a0194fb8ea155c80152fb101f543569#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by rarkins** [comment]
-   Upgrade type seems clearly relevant, e.g. is it a patch, minor or major dependency upgrade?
-   Dependency type also seems relevant, e.g. devDependency upgrades far less impactful than dependency ones
-   There's a possibility, depending on renovate configuration, that multiple upgrade types or even dependency types could be in the same commit.

**Comment by hbetts** [comment]
It depends on how the dependency in question is exposed through the dependents API.

If the dependency's upgrade would allow consumers of the dependent project to do something they couldn't previously do, then, yes, that would be a minor release on the part of the dependent.

However, if the dependency added a new feature which is not used by the dependent, or does not enhance existing functionality used by the dependent, then no new release of the dependent is even necessary (Though my personal projects are setup to always release, so you'll see a lot of patch releases on my projects).

**Comment by hbetts** [comment]
> Dependency type also seems relevant, e.g. devDependency upgrades far less impactful than dependency ones

I would tend to agree with you that development dependencies will often not effect downstream consumers, so would rarely even warrant a patch.

However, while some development dependencies may be just a `chore` commit type, others, such as minifiers, or compressors, for front-end libraries, could fall into the `perf` type bucket, as they may lead to improved performance of the library by consumers.

**Comment by hbetts** [comment]
As a side note, I use `conventional-commits-detector` to know which commit convention a project is using.

It has [regex patterns](https://github.com/conventional-changelog/conventional-commits-detector/blob/master/lib/regex.js) for some of the popular conventions.

**Comment by rarkins** [comment]
> If the dependency's upgrade would allow consumers of the dependent project to do something they couldn't previously do, then, yes, that would be a minor release on the part of the dependent.

This sounds like something that `renovate` could never *reliably* guess at. 

> others, such as minifiers, or compressors, for front-end libraries, could fall into the perf type bucket

Also seems hard to guess, however it would be technically *possible* that `renovate` could have some form of whitelist of popular libraries that we know are not merely chore upgrades. Potentially painful to keep updated though, and problematic if people disagree.

**Comment by rarkins** [comment]
> (Though my personal projects are setup to always release, so you'll see a lot of patch releases on my projects)

Is there any scenario where a pre-baked "semantic commits" feature in `renovate` could remove the need for your own custom templates, or does your customisation go beyond merely semantic commit labelling?

**Comment by hbetts** [comment]
> Is there any scenario where a pre-baked "semantic commits" feature in renovate could remove the need for your own custom templates, or does your customisation go beyond merely semantic commit labelling?

I'm not sure I understand the question.

As this time I just rely on the default commit messages of `renovate`. So no distinction as to whether a `renovate` pull request patches or enhances my project.

Then, because I use tooling that auto releases all commits, every `renovate` pull request leads to a patch release.

**Comment by rarkins** [comment]
@hbetts thanks. I had mistakenly thought you overrode the commit message template and/or merge request name to achieve the same.

**Comment by rarkins** [comment]
I suppose that "chore:" is probably the best existing prefix for dependency updates, but even that is not perfect.

**Comment by rarkins** [comment]
I think the safest  default behaviour - if semantic commit messages are enabled - is "fix" for dependencies and "chore" for all other types. i.e. dependencies will force a patch release but devDependencies won't (for most). For renovate, I currently have it configured to patch for *any* master commit. Because it's an installed tool and not a required library, I don't think that frequent updates should be annoying to anyone, assuming it's not checked into anybody's package.json.

**Comment by destroyerofbuilds** [comment]
That seems reasonable.  :+1:
