### ISSUE TITLE
It doesn't update anything when package-lock.json is present

### ISSUE THREAD

**Issue by IGZgustavomarin** [singapore/renovate#315]
We are adding `package-lock.json` to our repos. But after that, `renovate` is not generating any new PR for packages that we know have new versions.

Is there any option/config needed to force the updates? Is this the right behavior? How we should proceed?

**Comment by rarkins** [comment]
@IGZgustavomarin do you have any private npm modules in your `package.json`?

**Comment by IGZgustavomarin** [comment]
Yes, almost on every repo. We have them scoped and setup on `.npmrc`. Example: 
```
// package.json
   "@mycompany/module1": "1.0.0"

// .npmrc
@mycompany:registry=https://npm.mycompany.com/
``` 

Are only those the deps that are not updating?

**Comment by rarkins** [comment]
Is the `.npmrc` checked into the repository, or is it configured on the machine that's running `renovate`?

I just minutes ago committed a feature/fix so that renovate will look for presence of `.npmrc` checked into repos and use that for authenticating with npm registries.

**Comment by rarkins** [comment]
Please try version 8.35.0 because maybe that just solves it. If not, then we can drill down further.

**Comment by rarkins** [comment]
Anyway, please update to the latest and if still not working then perhaps you can send me more details and/or log with debug enabled.

For example: if the package.json includes both public and private modules, are all of them failing to update?

npm authentication is needed in two parts:

1. When we initially look up each module to see if there are updates. If authentication or lookup fails here, we simply don't upgrade that module but it doesn't impact any others.

2. When generating the `package-log.json`, `npm` itself needs the right registry/authentication to install. If this fails for any module, then that means lockfile generation will fail for *every* module - private and public. In such a case, *all* modules in the package.json - both private and public - will fail to update, because we consider lockfile updating to be a mandatory part of the PR

**Comment by IGZgustavomarin** [comment]
No luck with `8.35.0`. Our `.npmrc` is not on each repo, but is copied before running renovate task. 

I cannot post full log, but I'm getting some error like these: 

```
npm infverbose:  Error: ENOENT: no such file or directory, open '/builds/maverick-tools/renovate-npm-dependencies/tmp-111k39tq3WOJd39/package-lock.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/builds/maverick-tools/renovate-npm-dependencies/node_modules/renovate/dist/helpers/npm.js:18:24)
    at next (native)
    at step (/builds/maverick-tools/renovate-npm-dependencies/node_modules/renovate/dist/helpers/npm.js:90:191)
    at /builds/maverick-tools/renovate-npm-dependencies/node_modules/renovate/dist/helpers/npm.js:90:437
    at Object.<anonymous> (/builds/maverick-tools/renovate-npm-dependencies/node_modules/renovate/dist/helpers/npm.js:90:99)
    at Object.generateLockFile (/builds/maverick-tools/renovate-npm-dependencies/node_modules/renovate/dist/helpers/npm.js:36:17)
    at Object.<anonymous> (/builds/maverick-tools/renovate-npm-dependencies/node_modules/renovate/dist/helpers/npm.js:50:56)
```

```
error: Error updating branch renovate/all: Error: Could not generate new package-lock.json file
debug: Processing repository: {
  "repository": "maverick-modules/client-ip",
  "token": null,
  "platform": "gitlab",
  "onboarding": false,
  "endpoint": "https://gitlab.xxxx.io/api/v3",
  "packageFiles": []
}
```

I'll also try to update the runner image to node 8 instead of 6.9

**Comment by rarkins** [comment]
So the `.npmrc` is copied to the same directory that our are running renovate from? If so then it's probably the case that `npm` cant "see" that file when we spawn it into a tmp directory. I can think how to probably fix this, but you could also try putting the file in the process's home dir to see if that works too

**Comment by IGZgustavomarin** [comment]
We are copying `.npmrc` to the runner's home, so it should be accessing it.

Anyway, I think we've found the issue. Our `.npmrc` had an entry to
```
//INTERNAL_IP/:_authToken="VALID_AUTH_TOKEN="
@maverick:registry=https://npm.DOMAIN.io/
```

And now is changed to this: 
```
//npm.DOMAIN.io/:_authToken="VALID_AUTH_TOKEN="
@maverick:registry=https://npm.DOMAIN.io/
```

Both with the domain name instead of IP. And it seems to work fine. I wasn't failing before because of `node_modules` being cache.

**Comment by rarkins** [comment]
OK, great news. I guess it's not too annoying for the `.npmrc` to be in the home dir anyway.
