### ISSUE TITLE
Recreate unmergeable Pull Requests

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#32]
If real users have updated a renovate branch, then it wouldn't be a good idea to close or delete the existing branch. But let's say a PR is out of date or-  worse still - conflicted with the base branch, as often happens when updating adjacent dependencies. In such scenarios, would people prefer that we delete the old PR and create a new one? I don't think that rebasing the branch is possible via API, let alone in a non-interactive way. It might be possible to do the equivalent of a "force push" for a branch though.

**Comment by rarkins** [comment]
GitHub API can tell us these characteristics of a PR:

```
  "mergeable": false,
  "mergeable_state": "dirty",
  "commits": 1,
  "additions": 1,
  "deletions": 1,
  "changed_files": 1
```

There may be multiple commits - all by the renovate bot - so we can't use that easily.
But I think if mergeable is false, and changed_files = 1, then that has to mean that only the package.json file has changed and we should be safe to delete the branch/PR and recreate.

**Comment by rarkins** [comment]
It seems possible to manually update an existing branch to match the current master SHA. However, doing so results in the existing PR for that branch being closed:
![image](https://cloud.githubusercontent.com/assets/6311784/21947631/71301c58-d9e6-11e6-9bb2-46017f647af7.png)

I suppose it would then be possible to add a commit to that branch and then reopen the PR, but would that be much better than starting from scratch?

I also wonder if it's possible to update the file first and then point the existing branch to the new SHA, so that it doesn't merge close?

**Comment by rarkins** [comment]
It seems that branch is required when adding a file: https://developer.github.com/v3/repos/contents/#update-a-file

But you also need to provide SHA of the file being replaced. I wonder if you can provide the SHA of the package.json in current master, but the branch is the old existing branch?

**Comment by singapore** [comment]
Renamed this, as I think recreating stale PRs might cause far too many branches/PRs. Instead, this should be an option - disabled by default - to delete/create a PR if it becomes unmergeable and hasn't been modified apart from package.json.

**Comment by rarkins** [comment]
```
  "mergeable": false,
  "mergeable_state": "dirty",
  "commits": 1,
  "additions": 1,
  "deletions": 1,
  "changed_files": 1
```

I missed this before: if additions and deletions are `1` then clearly the only thing that's been modified is this dependency.

**Comment by rarkins** [comment]
The first feature we could therefore add is: "If pr.mergeable = false, and pr.additions + pr.deletions = 2, then delete the branch to allow a new PR". We need to make sure this doesn't cause any conflicts with our "recreatePrs" setting.

**Comment by rarkins** [comment]
This is now supported. Although it's configurable, I decided that it's best to enable this behaviour by default, so bumped the major version number to 4.
