### ISSUE TITLE
Automerge without tests

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#351]
Currently, automerge treats lack of status checks on a branch as not ready for automerge, but some repositories without tests may still want dependencies renovated. 

We can't simply treat "no status checks === success" because there may be a race condition where we create a branch and no status checks exist yet. And if GitHub have some latency or a CI service is slow to set its status check then we don't want to blindly automerge. 

So can we somehow detect lack of tests, or add safeguards (eg minimum 5 min delay between branch creation and automerge)?

**Comment by rarkins** [comment]
Example: repo with no tests enables renovate and has 20 pinned PRs outstanding. Nice if renovate could automerge those.

**Comment by hbetts** [comment]
A time-based delay touches on the halting problem. There's no way to know how long to wait for a status check to be posted.

**Comment by rarkins** [comment]
@hbetts I think we can wait indefinitely for status checks to go from Pending status -> Completed (success or failure) - that part is OK. The challenge is how long to wait for GitHub and GitLab to go from "no status checks" to Pending. We know this can't be instant (creating a branch is a git operation, which must trigger some callbacks on their side, etc, etc) and we know it *normally* is quick, but we must consider the edge case (e.g. TravisCI is temporarily down so is not setting its status check to pending immediately).

If we were to make sure that we never automerge in the same "cycle" of renovate where we've created the branch, then that would solve the non-instant problem. And if renovate runs hourly then that should solve the 99.9% of cases where status checks are set to pending within the hour. If we were to add a deliberate delay (e.g. 24 hours) then that should solve 99.999%, I suspect.

However I'd ideally still like a deterministic solution rather than relying on timing.

**Comment by kayoub5** [comment]
Each status check have a "context", that serves as a unique identifier, you can either compare the checks of the branch to be merged, with the checks of the base branch, or statically configure the checks to wait for (example: `continuous-integration/jenkins`)

------
https://developer.github.com/v3/repos/statuses/

**Comment by rarkins** [comment]
@kayoub5 thanks for the info. I have raised #359 (Configurable status checks for automerge) as I think that is a feature on its own.

What I'd like to have is this:

1. If a repo has status checks, then default behaviour is not to automerge unless they all pass
2. Config can override which status checks must pass before automerge
3. If repo has no status checks at all, then automerge right away

By default automerge is off, so it's not asking too much to expect users of repositories without tests to also configure the "null" status checks option, once available. However I was also hoping to automerge initial "pin" PRs, including for repos without tests and without them having to configure the null status checks option. 

Alternative 1: By default, combine all pinning into a single branch/PR. After all, it should not produce any different result to running `npm install` with ranges
Alternative 2: Just make the commit/merge.

**Comment by rarkins** [comment]
I have improved the onboarding logic so that all dependency "pins" will be combined into a single PR with automerge enabled. Therefore, someone without tests in their repo just needs to merge a single PR.

**Comment by rarkins** [comment]
This now works if someone sets `requiredStatusChecks` to null

**Comment by pixelastic** [comment]
*Sorry to revive this old thread, but it seemed more relevant than opening a new one.*

My understanding is that `requiredStatusChecks` set to `null` will completely bypass the checks: it will automerge if there are no checks, or if they fail, or if they succeed.

Is there a way to have renovate automerge if 1/ there are tests and they pass or 2/ there are no tests. 

I'd like to use the same shared renovate configuration on several projects, where some have tests and other don't. 

I could currently set `requiredStatusChecks` on the projects that don't have tests, but it seems like a pretty dangerous option to enable (in case I later add checks and forgot to remove this option).

**Comment by rarkins** [comment]
Currently it's not possible to have that because Renovate can't reliably determine if there are no tests. If GitHub had an outage with webhooks for example then you might see no status checks because the CI or other bots didn't know to run. Renovate automerges immediately when requiredStatusChecks is null because users complained when it didn't.

**Comment by pixelastic** [comment]
Thanks! That clarifies things. I'll manually add `requiredStatusChecks` on the projects I know don't have tests.
