### ISSUE TITLE
Clean

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#40]
Option to clean up all branches/PRs created by the renovate account?

**Comment by hbetts** [comment]
If I were testing `renovate`, a `clean` feature would be useful to quickly reset a repository, by removing all branches and pull requests created by `renovate`, so that I could quickly tweak and retest `renovate` configuration options.

**Comment by rarkins** [comment]
The main worry I had with this one was:
- The identity used for `renovate` is being used by a "real" user too
- We accidentally close some "real" PRs too

I guess though that this is an edge case and there would be little harm in writing a simple version of clean that closes any PR created by the `renovate` user and removes all branches.

**Comment by hbetts** [comment]
I would be concerned about closing pull requests opened by a real user as well.

Could clean close pull requests and branches matching the pattern used by `renovate`?

**Comment by rarkins** [comment]
Renovate now cleans up any orphan PRs or branches that shouldn't be there. I won't implement any further explicit clean
