### ISSUE TITLE
Clean up orphan branches/PRs

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#426]
Example use case:

1. Dependency "foo" has update available from 1.0.0 to 1.0.1
2. Renovate creates branch `renovate/foo-1.x` and associated PR
3. "foo" is removed as a dependency in base branch
4. Expected action: Renovate should delete the branch/PR the next time it runs

**Comment by rarkins** [comment]
Cc @mbrevda

**Comment by rarkins** [comment]
In the default use case, implementing this might be simple:
- Look for all branches with `renovate/` prefix (or alternatively, every branch created by the renovate user account)
- Delete any of those (+ associated MR if on GitLab) if we didn't see it in our list of branches during a run

However, a few of Renovate's other features make this a challenge to implement in the non-default use case:

1. Branches and PR titles can be *anything* due to ability to override templates
2. We can't know what the "full set" of branches should be if schedules are enabled

Working around (1) is fairly easy as we could allow a config branch pattern override for this feature. (2) makes it much harder and maybe even makes this feature impossible in a generic sense and therefore needing to implement specific use cases one by one.

In the above example use case, here is how we could distinguish this branch:

1. Its `package.json` list of dependencies is different to that of the base branch
2. It has a merge conflict with base branch (same line in `package.json` deleted and modified)

Neither of those alone - or together - is enough for us to be 100% sure we should delete the branch though. To solve the specific use case we might need the strict logic of "if the modified dependency no longer exists in the base branch".

**Comment by rarkins** [comment]
Lowering this to pri4 because the only identified use case (clean up renovate branch/PR if dependency no longer exists in base branch) should be a fairly rare one, and the impacts are very minor (the branch/PR will remain until someone notices and removes them).

**Comment by mbrevda** [comment]
I dont know how renovate knows after a push to the base branch which packages already have open PR's and which don't. What that mechanism, if renovate determines that a package that was in `HEAD^` is no longer in `HEAD`, and there is an open PR, can't it simply close it?

**Comment by rarkins** [comment]
After renovate runs on a repository, we can easily know all renovate branches that should exist except for ones not scheduled at that time. 

We can obtain a list of renovate branches that do exist from GitHub either based on the branch creator (e.g. renovate bot account) or a known branch prefix (e.g. "renovate/")

The delta between those two lists should be either:
- branches created previously on a schedule, or
- branches of "orphan" dependencies that have since been removed from the base branch (PR exists too), or
- branches remaining after a PR was merged or closed

I can't think of a way to identify branches of the first type only, which means we instead need a way to identify the other two types. It's probably achievable.

**Comment by rarkins** [comment]
As described, this issue has a lot in common with #428 and probably should be implemented together.

**Comment by rarkins** [comment]
To detect an orphan PR:

- download/parse all package json files from the branch 
- check that each dependency in the branch exists in the same package file in the base branch
