### ISSUE TITLE
Allow to configure main branch

### ISSUE THREAD

**Issue by fzaninotto** [singapore/renovate#443]
Hi! And kudos for the service, it really shines.

[One of my repos](https://github.com/marmelab/admin-on-rest) uses two long living branches: `master`, where I merge only bugfix PRs, and `next`, where I merge PRs adding new features. Every once in a while, I merge `next` into `master` and release a new version to npm.

It's a pretty usual workflow (e.g. see [material-ui](https://github.com/callemall/material-ui)), and I'd love to use renovate on that repo. But for that, I need to be able to configure on which branch renovate should focus - in my case, `next` and not `master`.

Is it something you might consider?

**Comment by rarkins** [comment]
@fzaninotto thanks for the suggestion. This looks achievable. Are you using a self-hosted renovate instance currently or the [GitHub App](https://github.com/apps/renovate) that I run? I will aim for support for both when implementing.

I think we still might require that any `renovate.json` for a repository lives in the `master` branch though, as otherwise in a hosted situation I can't think of how to otherwise "discover" that the repository should use a separate target branch for pull requests.

**Comment by fzaninotto** [comment]
Yes, I'm using your GitHub App. 

And I agree that to enable renovate on `next`, the JSON file should exist on master - it makes perfect sense.

**Comment by rarkins** [comment]
@fzaninotto this is now released and available via the GitHub App. Please update the `renovate.json` in your `renovate/configure` branch and add the line:
```
  "baseBranch": "next",
```

The next time renovate runs you should see a new line added in the description, like:

> You have configured renovate to use branch `next` as base branch.

Once you are happy with the config and merge the `renovate.json` to `master`, you should see that the "Pin all dependencies" you later get will target branch `next`.

Also note: renovate is configured to create PR only once tests are complete, so in the first run you might notice the branch created and in the second run a PR.

**Comment by fzaninotto** [comment]
So Renovate passed again on [my repo](https://github.com/marmelab/admin-on-rest/pull/829) and added the sentence you mention. However, it seems that the list of changes is still based on the `master` branch. E.g it suggests upgrading `webpack`, which is not in the `package.json` anymore in `next`...

**Comment by rarkins** [comment]
@fzaninotto thanks for the feedback. This has been updated in the latest run: https://github.com/marmelab/admin-on-rest/pull/829

**Comment by rarkins** [comment]
FYI this was only a "cosmetic" problem in the *onboarding description* - I verified earlier with a fork of your repo that the actual PRs created would be based off `next` not `master`.
