### ISSUE TITLE
Deploy to AWS (lambda)

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#45]
Like LambCI is doing: https://github.com/lambci/lambci

**Comment by rarkins** [comment]
https://aws.amazon.com/blogs/compute/introducing-simplified-serverless-application-deplyoment-and-management/

**Comment by khornberg** [comment]
I am interested in this going to lambda. Does the build step make the resulting Javascript compatible with Node 4.3?

http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by rarkins** [comment]
@khornberg unfortunately it does not work with 4.x. I tried and found it wasn't simple so didn't continue further. IIRC it's mostly the async/await code that's the problem as it's not as simple as telling babel "hey transpire this to 4.x"

**Comment by khornberg** [comment]
Ok, I guess Lambda will have to wait for AWS to update the environment

**Comment by khornberg** [comment]
https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/

**Comment by rarkins** [comment]
I haven't tested with 6.10 but assume it will work. The question then is what level of packaging should we do within this repo? Eg define a cloudformation stack?

**Comment by khornberg** [comment]
My initial thought is that nothing in this repo needs to change.
Deploying to lambda is an implementation of `renovate` on a specific platform.

**Comment by rarkins** [comment]
I've added some minor configuration to allow it to be deployed to Heroku out of the box, so don't mind the same for other major platforms too. 

Either way, please keep me updated with your progress!

**Comment by rarkins** [comment]
I'm not sure if the part of renovate where we spawn npm or yarn is compatible with lambda

**Comment by rarkins** [comment]
Unlikely to be possible for some time because we need to be able to run `npm` and/or `yarn` from the CLI.
