### ISSUE TITLE
Cannot get PR labels applied

### ISSUE THREAD

**Issue by SpainTrain** [singapore/renovate#459]
Great project :heart: 

version: 9.10.2

We are having an issue getting labels applied to renovate PRs.  The config appears correct in both the main configuration file and the renovate.json file in the repo, but neither cause labels to be applied when PRs are opened.

Every other config property seems to be working correctly.

Please let me know if I am missing something obvious here.  Otherwise I can get some logs with `debug` or `silly`.  FWIW, labels *were* working with the Github App.

#### Main configuration file

`$ heroku run cat config.js -a <project name>`

```
module.exports = {
...
  "labels": ["renovate", "current iteration"],
...
```

#### repo `renovate.json` file

```
$ cat renovate.json 
{
  "enabled": true,
  "depTypes": ["dependencies", "devDependencies", "optionalDependencies"],
  "labels": ["renovate", "current iteration"],
  "assignees": [],
  "reviewers": []
}
```

**Comment by rarkins** [comment]
In the configs you provided, `labels` appears to be the only non-default configuration option, so therefore it's possible theoretically that the config is being ignored altogether. However if you've tried both `config.js` in heroku (something I haven't tried myself FWIW - I go with their "12 factor" approach of using env) as well as `renovate.json` in the repository, then it's probably not config.

One thing to note when you are troubleshooting this: labels are only applied at PR *creation* and will never be updated after that. e.g. if you are expecting an existing PR to have labels applied after you change configuration, then that will never work regardless of if there's a bug. The reason for this is that people might add/remove labels so not changing them after PR creation seemed the safest behaviour for the regular use case.

**Comment by rarkins** [comment]
The decision of whether to apply labels is made here: https://github.com/singapore/renovate/blob/master/lib/workers/pr/index.js#L131-L133

The GitHub implementation is here: https://github.com/singapore/renovate/blob/master/lib/api/github.js#L360-L365

If you capture logs at debug level (`heroku config:set LOG_LEVEL=debug`) then you should always see this line: `logger.debug(`Creating PR for branch ${branchName}`);` and if labels are functioning correctly then you'd also see `logger.debug(`Adding labels ${labels} to #${issueNo}`)`.

**Comment by SpainTrain** [comment]
Thanks for the quick reply.

> I go with their "12 factor" approach of using env

Sorry, I should have provided full context - env is how the rest of the config is set, and originally I tried setting labels via env.  When env didn't work, I tried via CLI.  And finally now via `config.js`.  I will revert back to env since CLI and `config.js` didn't solve this.

I have only been testing with newly created PRs, so unfortunately that's not the issue here.

Thanks for the pointers, that will allow me to quickly dig in deeper and figure this out.

**Comment by rarkins** [comment]
I just checked the one repo where I have renovate applying labels with the GitHub App, and it looks like they may not be taking effect there either. Please leave it with me and save yourself the time of digging deeper for now.

**Comment by SpainTrain** [comment]
Sounds good.

Still happy to provide logs if helpful.

Thanks!

**Comment by rarkins** [comment]
I could reproduce and a fix is being tested by CI.

We were JSON.stringify'ing the labels array when passing to ghGot, but since their last major release they supported supplying objects or arrays only. I haven't verified but it probably broke in 8.51.1: https://github.com/singapore/renovate/commit/53170cb411f53ee027d9551bc71786c3c8347f1c

Example reproduction:

```
^[[34mDEBUG^[[39m: Adding labels 2-ready,pri3-normal to #6776^[[90m (repository=singapore/keylocation)^[[39m
^[[31mERROR^[[39m: Failed to ensure PR: TypeError: options.body must be a plain Object or Array when options.form or options.json is used
           at normalizeArguments (/app/node_modules/got/index.js:320:10)
           at got (/app/node_modules/got/index.js:386:20)
           at ghGot (/app/node_modules/gh-got/index.js:38:9)
           at Function.ghGot.(anonymous function) [as post] (/app/node_modules/gh-got/index.js:64:28)
           at Object.addLabels (/app/lib/api/github.js:362:15)
           at Object.ensurePr (/app/lib/workers/pr/index.js:132:24)
           at <anonymous>
           at process._tickCallback (internal/process/next_tick.js:169:7)^[[90m (repository=singapore/keylocation, branch=renovate/angular)^[[39m
```

**Comment by SpainTrain** [comment]
:+1: 

I have seen that error in the logs, but didn't think to add it to the original ticket (doh!).  Was going to open as a separate ticket the next time I saw it in logs.

Thanks again for tracking this down.

**Comment by rarkins** [comment]
No problem, and sorry for the inconvenience. It should now be fixed in npm version 9.10.3

**Comment by SpainTrain** [comment]
you are awesome

**Comment by SpainTrain** [comment]
@rarkins 

I am still having trouble on `v9.17.2`

![selection_549](https://user-images.githubusercontent.com/380032/28182472-491f8046-67da-11e7-9960-15f7798a564e.png)

Does that look right?  I have removed `config.js`, so env is the only source of config.  I also saw the familiar error in the log:

```
ERROR: Failed to ensure PR: TypeError: options.body must be a plain Object when options.form or options.json is used
           at normalizeArguments (/app/node_modules/got/index.js:320:10)
           at got (/app/node_modules/got/index.js:386:20)
           at ghGot (/app/node_modules/gh-got/index.js:38:9)
           at Function.ghGot.(anonymous function) [as post] (/app/node_modules/gh-got/index.js:64:28)
           at Object.<anonymous> (/app/node_modules/renovate/dist/api/github.js:422:17)
           at next (native)
           at step (/app/node_modules/renovate/dist/api/github.js:891:191)
           at /app/node_modules/renovate/dist/api/github.js:891:437
           at Object.<anonymous> (/app/node_modules/renovate/dist/api/github.js:891:99)
           at Object.addLabels (/app/node_modules/renovate/dist/api/github.js:428:19)
```

**Comment by rarkins** [comment]
@SpainTrain definitely looks like the same problem somehow. I'll take a look.

**Comment by rarkins** [comment]
@SpainTrain actually I can't reproduce this. I thought it might be the spaces in your env values but for me the following worked:
`RENOVATE_LABELS="a,b c" npm run start-babel renovate-tests/no-lockfiles`

![image](https://user-images.githubusercontent.com/6311784/28183452-d0bd9404-680f-11e7-9cac-966061641889.png)

**Comment by SpainTrain** [comment]
k, I will up the log level and collect more info

**Comment by rarkins** [comment]
Please run at debug or trace level and look for "Adding labels" in the logs

**Comment by rarkins** [comment]
If you are able to experiment, also try adding `labels` configuration to the destination repo's `renovate.json` or `package.json` so we can see if that works or not.

**Comment by SpainTrain** [comment]
```
DEBUG: Adding labels renovate,current iteration to #124 (repository=****)
ERROR: Failed to ensure PR: TypeError: options.body must be a plain Object when options.form or options.json is used
           at normalizeArguments (/app/node_modules/got/index.js:320:10)
           at got (/app/node_modules/got/index.js:386:20)
           at ghGot (/app/node_modules/gh-got/index.js:38:9)
           at Function.ghGot.(anonymous function) [as post] (/app/node_modules/gh-got/index.js:64:28)
           at Object.<anonymous> (/app/node_modules/renovate/dist/api/github.js:422:17)
           at next (native)
           at step (/app/node_modules/renovate/dist/api/github.js:891:191)
           at /app/node_modules/renovate/dist/api/github.js:891:437
           at Object.<anonymous> (/app/node_modules/renovate/dist/api/github.js:891:99)
           at Object.addLabels (/app/node_modules/renovate/dist/api/github.js:428:19)
```

I have `renovate.json` setup with labels for one of the repos.  Labels are not working on that repo either unfortunately.

**Comment by rarkins** [comment]
This is not easy to reproduce at my end. I ran `RENOVATE_LABELS="renovate,current iteration" renovate renovate-tests/no-lockfiles` and it works fine. Log: `DEBUG: Adding labels renovate,current iteration to #18 (repository=renovate-tests/no-lockfiles)`

What do you see when you search your logs for "versions"? You should see a lot of lines like `"versions": {"renovate": "9.17.2", "npm": "5.2.0", "yarn": "0.27.5"},`

**Comment by SpainTrain** [comment]
Roger.  I am doing some debugging on my end to try to figure it out as well.

```
yarn run v0.27.5
$ renovate
DEBUG: Parsing configs
DEBUG: Could not locate config file
DEBUG: File config
       {}
DEBUG: CLI config
       {}
DEBUG: Env config
       {
         "logLevel": "debug",
         "autodiscover": true,
         "pinVersions": false,
         "rebaseStalePrs": true,
         "prCreation": "not-pending",
         "commitMessage": "[Template]",
         "prTitle": "[Template]",
         "labels": ["renovate", "current iteration"]
       }
 INFO: Autodiscovering GitHub repositories
DEBUG: getRepos(token, endpoint)
DEBUG: Detecting versions
DEBUG: Detected versions
DEBUG: Versions: {"renovate":"9.17.2","npm":"3.10.10","yarn":"0.27.5"}
```

**Comment by rarkins** [comment]
I've also verified that labels are being applied (as expected) for users of the GitHub App.

**Comment by SpainTrain** [comment]
Quick question, what version of node are you testing with / using for the Github App?  We are running 6.11.1.

My debugging has been confounding.  I added `_.toArray(labels)` to https://github.com/singapore/renovate/blob/master/lib/api/github.js#L366 just to ensure that an array was definitely being passed as `body` (since Array is allowed at https://github.com/sindresorhus/got/blob/master/index.js#L318).  However, I *still* receive that same error.  I didn't think it was possible that `Array.isArray(_.toArray(<arrayLikeObj>))` could return `false`.

LMK if you have any suggestions.   I am going to keep digging to figure this out.  Thanks!

**Comment by rarkins** [comment]
The GitHub App runs on node v8.x while locally I've still been running v6.9.4. I really am out of ideas as to why you could be seeing this. The most obvious idea is "something is not the same version as you think it is" but after all the debugging you've done and using different platforms/installs, that seems a lot less likely.

BTW if you are running the source locally:
- Make sure to use the `npm run start-babel` version so that it runs out of `lib/` and not out of `dist/`, as `dist` won't get updated unless you manually run `npm run build` after each code change.
- Install with `yarn` to make use of `yarn.lock` and reduce one more possibility

**Comment by rarkins** [comment]
To what extent is this reproduceable?  Is it every single repository you use? Can you copy your package.json (sanitize if necessary) to a public repo and get the same problem? If so then you could add me as collaborator and I see if I get the same problem when renovating it from my client.

**Comment by SpainTrain** [comment]
I agree that version discrepancy is the most likely suspect, but I have checked everything I can think of (including matching line numbers in stack traces).

Thank you for the tips.  I have actually been running on Heroku and pointing to a branch on my fork (with `dist` checked in).  The line numbers in stack traces (and version printed out) have matched `dist` in my branch, so I think that bit is working as I think it is.

Great idea re: adding as collaborator, and we actually have a perfect repo for it.  Once I have finished my current test run, I will set it up (unless the test reveals some new info).  Thanks!

**Comment by rarkins** [comment]
By default I think heroku will use the command in the `Procfile`, i.e. `yarn run start-raw`so actually it will run out of `lib/`

**Comment by SpainTrain** [comment]
Mind = blown:

```
Jul 14 13:48:19 renovate-homezen app[run] DEBUG DEBUG: Adding labels renovate,current iteration to #26 (repository=homezen/homezen.github.io)
Jul 14 13:48:19 renovate-homezen app[run] DEBUG DEBUG: [ 'renovate', 'current iteration' ] (repository=homezen/homezen.github.io)
Jul 14 13:48:19 renovate-homezen app[run] DEBUG DEBUG: Adding labelsArr renovate,current iteration to #26 (repository=homezen/homezen.github.io)
Jul 14 13:48:19 renovate-homezen app[run] DEBUG DEBUG: [ 'renovate', 'current iteration' ] (repository=homezen/homezen.github.io)
Jul 14 13:48:19 renovate-homezen app[run] DEBUG DEBUG: labelsArr isArray: true (repository=homezen/homezen.github.io)
Jul 14 13:48:19 renovate-homezen app[run] ERROR ERROR: Failed to ensure PR: TypeError: options.body must be a plain Object when options.form or options.json is used
```

The versions of gh-got and got are 6.0.0 and 7.1.0 respectively.

I added you to a repo (`cdnpm`) that we do not use any longer, so feel free to mess with it as needed for testing.  Additionally, I added you as a collaborator to the heroku project repo so you can see how it is configured.  ***Thank you*** for all your help!

**Comment by SpainTrain** [comment]
Figured this out, not sure why but `npm ls` lied to me about the installed version of `got`.

```
Running npm ls got on ⬢ renovate-homezen... up, run.2931 (Standard-1X)
renovate-homezen@1.0.0 /app
`-- renovate@0.0.0-homezen-testing invalid
  `-- got@7.1.0  extraneous
```

but actually

```
Running head /app/node_modules/got/package.json on ⬢ renovate-homezen... up, run.4661 (Standard-1X)
{
  "name": "got",
  "version": "7.0.0",
```

`Array` support was added in `got` release `7.1.0` (https://github.com/sindresorhus/got/releases / https://github.com/sindresorhus/got/pull/335)

This really shouldn't happen given that you pin `got` in package.json, but I can hunt it down from here and fix it.  Closing since this is a Heroku deployment issue for us, not an issue with the repo.

Thanks again for your help!
