### ISSUE TITLE
Support interactive mode

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#46]
CLI `--interactive`

Allow the user to accept or skip each dependency. If they skip a dependency, give them the option to permanently ignore it.

**Comment by hbetts** [comment]
If you allow the user to permanently ignore a dependency, will that require `renovate` to maintain state outside of the existing use of branches and pull requests?

**Comment by rarkins** [comment]
We support ignoring dependencies in config today, so my idea was to prompt them about where to configure it (eg `package.json`) and raise a PR for that. Ie I'd consider it config and not "state".

**Comment by hbetts** [comment]
Ah, then that makes sense, and I like the idea of capturing the user input in the form of pull requests updating the configuration.

**Comment by rarkins** [comment]
I think the onboarding PR is now clear enough that this is not necessary.
