### ISSUE TITLE
Question about GitHub "App"

### ISSUE THREAD

**Issue by khornberg** [singapore/renovate#474]
I see
>Renovate is now available as a free GitHub "App". Go to [github.com/apps/renovate](https://github.com/apps/renovate) to enable it now.

What does that mean? Where does `Renovate` run? Is that a way to only authorize a self hosted `renovate` deployment.

**Comment by rarkins** [comment]
I run a Renovate instance used for the GitHub app currently on Heroku although plan to move it to AWS shortly. It only runs on repositories that install/enable it via the apps link. 

If you want self hosted, I recommend just running using your own dedicated GitHub bot user and using `--autodiscover` in the CLI arguments to tell Renovate to check every repository that the bot account is authorised to see.

**Comment by rarkins** [comment]
Ie the renovate app run by me has no access to your repositories unless you go to effort to install/authorise it.

**Comment by khornberg** [comment]
Ok that was what I was thinking but wanted clarification. Thanks :)
