### ISSUE TITLE
Support single branch/PR for all dependencies

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#48]
Current behaviour (non-configurable) is one branch/PR per dependency.

**Comment by rarkins** [comment]
Workaround is described here: https://github.com/singapore/renovate/blob/master/docs/design-decisions.md#separate-branches-per-dependency

**Comment by rarkins** [comment]
Maybe we should *default* to this? e.g. first time someone runs `renovate`, it could be overwhelming if they have 10+ PRs (even if that is maybe a good thing). It might be feasible to adopt this approach:

- Add a "single branch" configuration option
- Default single branch to true
- As part of the PR body for this, include a description for how to change the setting in `package.json` or `renovate.json`
- Maybe even raise a second PR (once only), with commits for enabling multiple branch support

Importantly: what behaviour when there are multiple `package.json` files in the repo? Would people still prefer a single branch for all? I'd assume not

**Comment by hbetts** [comment]
As explained in [bullet point three](https://github.com/integration/greenkeeper) in the GreenKeeper integration, GreenKeeper sends a single initial pull request to update all out of date dependencies, and from then on, sends a single pull request per dependency.

What would be the process of changing the default for those that are running `renovate` exclusively with command line arguments through a cron-like platform?

**Comment by rarkins** [comment]
> What would be the process of changing the default

To answer this literally, they could do this via config file, environment variable, `package.json` entry, or dedicated `renovate.json` in the target repository. Making the setting in the target repository (via `package.json` or `renovate.json`) would be preferred.

It's been my assumption that anyone using this tool would/should try it manually first, so perhaps that opens up other possibilities for "onboarding" (e.g. an `--init` CLI option)

**Comment by hbetts** [comment]
I meant to say that I would prefer to run, and configure, `renovate` exclusively through command line arguments.

For example, I would like to run `renovate` over projects within a single group, where each project may be owned by a different team. I would not expect those teams to use, themselves, `renovate`. Therefore, placing a configuration file within their project, or modifying their `package.json` file would be undesirable.

**Comment by guumaster** [comment]
This would be a great adition. When `renovate` finds lots of dependencies to update I had to close them and do it manually, having an option to generate single PRs would be great.

**Comment by rarkins** [comment]
@guumaster:

> I had to close them and do it manually

Do you mean that in your regular use of `renovate`, you prefer to merge all changes as one commit, even if `renovate` has created separate PRs?

I'm interested to understand the advantages of that approach. e.g. you prefer less commits to your master branch, or less CI builds, or .. ?

BTW I don't think `renovate` needs to be "opinionated" here and can support multiple approaches anyway - I'm just trying to understand the reasoning. In my case, I like to keep one branch per dependency to make testing plus potential future rollbacks simpler. I've definitely needed to roll back individual dependency updates at times when obscure bugs have later been found in production that weren't caught by tests.

**Comment by guumaster** [comment]
I'm working with 10~15 repos. Last week `eslint` package updated, that usually means that lots of `eslint-config-*` and `eslint-plugin-*` updates the same week. This is a common pattern for other packages too. Also, if you are using `yarn` it means that probably after the first or second merge you start to get conflicts in your PRs and can't do it automatically with the "merge" button anymore. So when that happens (two times last week) I preferred to close all PRs and back to update dependencies the old way (manually).

Also, is much more work if you need to merge 3 packages updates across 10 different repos, I'm talking 10 PRs to review/merge against 30 PRs.

That why I think that having an option, even per repository, to do single/multi PRs would be a nice to have feature for people with different workflows and preferences.

**Comment by rarkins** [comment]
@guumaster thanks for the information. 

I'm looking at multiple approaches to solving this problem. 
 - Automatic updating/resolving of merge conflicts
 - Grouping of related dependencies into one branch (#10)

In GitHub, we automatically "rebase" PRs whenever they get a merge conflict. Basically - update the files (package.json, yarn.lock) again from master and update the existing PR to point to the new commit. So personally I have renovate running every hour using a Heroku dyno so that's the maximum time I need to wait to have conflicted branches recreated. This same thing is not done for GitLab yet because it doesn't support the low level git API to enable us to "rebase" from master. As a result, we'd need to close the existing PR and create a new one. Perhaps this can be added behind a boolean config option so that people can turn it off if they're annoyed by too many closed/recreated PRs and prefer to fix conflicts manually.

I created issue #132 for this GitLab feature - please provide your comments

**Comment by guumaster** [comment]
Oh, now I why is harder to do in GitLab. Although, close/recreate would be messy.

 What do you think about doing it through an actual git command? There are JS implementations like [nodegit](https://www.npmjs.com/package/nodegit). Actually what you only need the API for is to do non git commands to manage the PRs, right?

**Comment by rarkins** [comment]
It would be pretty nasty to clone the entire repo in order to run these commands

**Comment by rarkins** [comment]
This is now supported via the `groupName` configuration. Example:

`renovate --group-name=all foo/bar`

This will create a branch `renovate/all` with all upgraded packages there.
