### ISSUE TITLE
Changelogs containing # create unnecessary references to the repository

### ISSUE THREAD

**Issue by michaelkruglos** [singapore/renovate#489]
## Description
When pull request from renovate is issued it contains changelogs of the dependencies, which sometimes contain references to the issue they fix, e.g. `Bump version to 1.0.9 to include #298`. In this case github thinks these are references to the issues in the repository in which the pull request is issued. This is undesirable since the repository becomes full of issue references, which don't have anything to do with the PR.

## Fix suggestion

Generate the changelog messages enclosed in `backticks` (`), this way it's going to appear as a regular text, rather than issue references.

## Example of the issue

 Soluto/tweek#470

<img width="661" alt="screen shot 2017-07-16 at 17 31 36" src="https://user-images.githubusercontent.com/3526988/28248393-adf774c8-6a4c-11e7-9d54-9fa89503a283.png">

**Comment by rarkins** [comment]
Thanks for reporting it. Previously these were being hyperlinked to the source repo but causing noise there, so functionality was removed for public repos. Your suggestion sounds fine and should be quickly implementable.
