### ISSUE TITLE
Lockfile maintenance config via env var?

### ISSUE THREAD

**Issue by SpainTrain** [singapore/renovate#515]
Is there a way to set the lockfile maintenance config via env vars?  It appears that the env var name cell is empty in that column in the docs.  Thanks!

**Comment by rarkins** [comment]
Because it's an object (i.e. with nested config inside), it's not possible currently to define via env. How were you wanting to modify the behaviour? I will think if there's a better way to allow it once I know your use case.

**Comment by SpainTrain** [comment]
Just want to disable it by default and only re-enable per repo.

**Comment by rarkins** [comment]
Ok I'll think of a way

**Comment by rarkins** [comment]
@SpainTrain it should be supported now - see https://github.com/singapore/renovate/commit/beb37bc1283a9cadd38f863110be15a55ab7026a and Renovate v9.24.0

**Comment by SpainTrain** [comment]
:tada: and thanks for quick turnaround!
