### ISSUE TITLE
rebaseStalePrs: should ignore PR that is already edited manually

### ISSUE THREAD

**Issue by ikatyang** [singapore/renovate#525]
For example, renovate makes a PR for new version of my linter-config package, which will usually cause build failed, I have to fix linter error in that PR before merging, but with `rebaseStalePrs` enabled it'll always override my edited branch (once per hour I think?), though I can just `git push -f` back from my local branch, it'd be better to not override those edited branch.

**Comment by rarkins** [comment]
Yes, I agree. I have a setting to detect if  PR has been modified and rebasing should check for this also.
