### ISSUE TITLE
Predefined package groups

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#536]
To save people reinventing the wheel with package patterns, support predefined patterns within renovate.

Proposal:
- Call them "packageGroups"
- Support `packages` syntax (i.e. packageNames, packagePatterns, etc).
- Can be used inside package rules
- Supports nesting but needs protection against infinite loops

This might be helpful for outputting list of matching packages: https://github.com/nice-registry/all-the-package-names

**Comment by mbrevda** [comment]
Isnt this done now with https://renovateapp.com/docs/deep-dives/config-presets?
