### ISSUE TITLE
Add 'patch' to automerge options

### ISSUE THREAD

**Issue by ikatyang** [singapore/renovate#537]
I'm writing a linter-config package, I'd like to disable those lint-plugin's automerge for feature updates (minor), only allow automerge for bug fix (patch) updates, so that I can update my rule settings and submit them together with the PR and won't be annoying from having to merge patch PR manually.

If you think this feature(?) is acceptable, I'd like to send a PR.

**Comment by rarkins** [comment]
It's a good idea and you're welcome to submit a PR. The only "problem" is that I think that patch support should be supported wider than just automerging and haven't yet decided the exactly how to do that. If it's fairly quick for you to support it for automerge though then please go ahead as it's unlikely to need too much refactoring later. 

BTW it may still not work exactly as you want. e.g. If you are running 1.0.0 and both 1.0.1 and 1.1.0 are available then you'll only see a PR for 1.1.0 and not both 1.0.1.  Maybe most people prefer that though? This is what I mean by "supported wider" - I have a feeling that full patch support would touch a lot of files.   Anyway if you are happy to implement just automerge patch for now then that would be useful!
