### ISSUE TITLE
Update stale PRs

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#54]
By "stale" I mean PRs that are no longer up-to-date with the base branch. This would happen every time someone makes a commit to `master`, for example - so I'm not sure if many people at all would want so many automated tests to be enqueued (e.g. 5 open renovations and 10 commits to master per day would result in 50 extra pull requests).

Probably best to wait for #52 first, at least.

**Comment by hbetts** [comment]
It would be preferred, in my case, if the tests executed for any `renovate` filed pull requests reflected the dependency update against the latest code in the `master` branch. Basically, I should have the confidence that accepting a passing pull request will not break the master branch. I'm not sure I see any way other than to refile pull requests.

Though your example assumes 5 `renovate` pull requests open, I would rarely assume more than maybe one of my dependencies requiring a change to `package.json` per week (Such as a major version bump). Therefore, accruing more than one or two outstanding `renovate` pull requests should be a rare situation.

That leaves the behavior of `renovate` with respect to lock files. That could be quite noisy (I have a few hundred projects depending on ~1000 dev dependencies in their dependency tree.).

**Comment by rarkins** [comment]
I've refactored commit/branch code tonight to take advantage of some of GitHub's lower-level API endpoints that I wasn't previously aware of.

When a `renovate` PR becomes *unmergeable*, on the next run it will now:
 - Create a new commit (updating `package.json`) off of the latest master
 - Update the existing branch reference to point to the new commit

This is essentially the same as rebasing it via git and is already in master.

For this issue #54, the question was whether to do it for "stale" PRs, by which I meant ones that were 1 or more commits behind master. It would be best practice to always update PRs to the latest master commit and test again before merging, but I'm sure many people don't do that. Once this is implemented, I will keep it disabled by default, otherwise people might see far too many branch updates (once per `renovate` branch, per commit to master).

**Comment by SebastienElet** [comment]
@rarkins could i PR the update of the PRs ? If yes, do you have any idea/requirement for the option name ?

**Comment by rarkins** [comment]
@SebastienElet I would like to make sure we both have the same idea.

Is it your desire that `renovate` will "rebase" any existing `renovate` PRs that have fallen behind `master`?

e.g. it would have the following implications:

Let's say you run `renovate` and it creates three PRs.
Then you merge one of them.
The next time `renovate` runs, it would rebase the two remaining PRs (which will cause two new builds on your CI).
Then you add some patch or feature to your code (unrelated to `package.json`).
The next time `renovate` runs, it will rebase the two PRs again (and two more CI builds).

**Comment by SebastienElet** [comment]
@rarkins this is exactly what i want 👍

**Comment by rarkins** [comment]
I think we maybe call the option `rebaseStalePRs` and default it to false. Add it around here: https://github.com/singapore/renovate/blob/master/lib/config/definitions.js#L67

Here is where we do the current checks: https://github.com/singapore/renovate/blob/master/lib/api/github.js#L180-L185

I think perhaps you can compare the existing PR's `base.sha` value to `config.baseCommitSHA` and if they are different then you can assume the old PR is "stale" and should be rebased.

And here's where we make the decision to rebase: https://github.com/singapore/renovate/blob/master/lib/worker.js#L158-L164

**Comment by SebastienElet** [comment]
Thx i try to push this tomorrow !
