### ISSUE TITLE
Performance: GitLab API Detection

### ISSUE THREAD

**Issue by hbetts** [singapore/renovate#544]
When querying GitLab to determine API version the query to version 3 takes a full minute (fetching owned projects).

Hopefully there's a more efficient way to detect API version - https://gitlab.com/gitlab-org/gitlab-ce/issues/35685

**Comment by rarkins** [comment]
Yes, I had noticed when running against the public API that it still took around 5 seconds for my 2 owned repositories.

**Comment by rarkins** [comment]
@hbetts I plan to start implementing breaking changes for renovate@v10 once node.js v8 reaches LTS (and drop support for babel/transpilation). What do you think about removing GitLab APIv3 support at that time too?

**Comment by hbetts** [comment]
@rarkins that would be fine with me. Technically GitLab had planned on removing v3 API support last month, but because of continued use of that API endpoint, they extended the deadline by some unspecified amount of time.

I would assume the GitLab team would appreciate you removing v3 support. :smile: 

There may still be a few users out there maintaining a sufficiently old enough version of GitLab that v3 is the only option, or for some other reason haven't made the transition.

So perhaps a patch on Renovate v9 with a warning that v3 GitLab support is going to be dropped?

Also, I read on one of the GitLab sites that they plan on a v5 endpoint in the mid-future. (Originally a REST gateway on top of GraphQL, but [looks like they recently dropped that plan](https://gitlab.com/gitlab-org/gitlab-ce/issues/34754))

(On a related note, v4 for GitLab.com works just fine - https://gitlab.com/hyper-expanse/generator-python-lib/merge_requests/6)
