### ISSUE TITLE
Use "v" prefix for versions in templates 

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#587]
Will make it more readable to change from 1.1.0 to v1.1.0, for example. 

Possible that semver works the same in all cases?

**Comment by rarkins** [comment]
@luftywiranda13 I think you also prefer this approach in your templates too?

**Comment by luftywiranda13** [comment]
yesss, I also override the default config for this 😄

**Comment by luftywiranda13** [comment]
I think it should be fine if renovate do this approach. 

so for example:
-  `1.1.0` -> `v1.1.0`
-  `4.2.1-beta3` -> `v4.2.1-beta3`

and in fact that in git [docs](https://git-scm.com/book/en/v2/Git-Basics-Tagging) they basically do it like this for tagging:
![screen shot 2017-08-03 at 16 09 01](https://user-images.githubusercontent.com/22868432/28914537-39a4d4ee-7866-11e7-9c49-ea587c5c05c4.png)

so I think it's already well-known and well-preferred
