### ISSUE TITLE
semantic-commits' subject text should be lowercase

### ISSUE THREAD

**Issue by luftywiranda13** [singapore/renovate#594]
`semantic-commits` or mostly known as `conventional commit message` is a convention derived from [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.uyo6cb12dt6w).

![screen shot 2017-08-03 at 15 30 22](https://user-images.githubusercontent.com/22868432/28913366-f6ddfa40-7861-11e7-9471-826cb17b0b0f.png)
![screen shot 2017-08-03 at 15 30 34](https://user-images.githubusercontent.com/22868432/28913367-f6e2aacc-7861-11e7-95bb-cdca747ca3be.png)

But why does `renovate` use capitalize letter for the subject? this is the reason why I override renovate's default config in my projects

**Comment by rarkins** [comment]
Could be solved with a simple toLowerCase?
For non semantic commit users I think it looks best to continue  with capitalisation so keeping the template the same and lowering it when semantic commits enabled might be the easiest approach.

PR welcomed too :)

**Comment by rarkins** [comment]
Could possibly be done with a handlebars helper (e.g. https://gist.github.com/there4/2903216) but may be easier in our own JS code prior to compiling the template.

**Comment by luftywiranda13** [comment]
yes I agree, should be lowercase only if semantic commits enabled.

I'm sorry but I never really dig down through this repo so I don't know exactly where to look 😣

**Comment by rarkins** [comment]
Needs a single line to convert prTitle template to lower case here: https://github.com/singapore/renovate/blob/db2e6dd1b982571bd70dc57e7ed6d1cd7a109b5b/lib/workers/repository/upgrades.js#L59

I can do/test later

**Comment by luftywiranda13** [comment]
or can't we do something like `(#if semanticCommits)...` like how `prTitle` does? https://github.com/singapore/renovate/blob/master/lib/config/templates/default/pr-title.hbs

**Comment by rarkins** [comment]
Yes but that will make the template even messier than it is today so I thought it's easiest to lower the case in JS instead of we plan to do it 100% of the time

**Comment by rarkins** [comment]
It's always a balance between template simplicity and DRY and I'm still working out the best balance. Eg could use separate templates for pin, major and minor to remove most of the template if statements but then there'd be a lot of duplication instead. 

I also don't like that people need to copy/paste long templates just to make small changes. Also means they don't get improvements/refactors of the base templates because they will keep overriding them. 

Considering how much to use "partials" for templates now.
