### ISSUE TITLE
Configure PR still adds `renovate.json` when you have it in package.json

### ISSUE THREAD

**Issue by charlike** [singapore/renovate#636]
I have and kinda prefer the config of it to be in the package.json. When it detects package.json to look for `renovate` field and only if there's no such field to add `renovate.json`.

_(btw, side question [not worth whole new issue] how to ignore pinning only specific package, like semantic release, which should be with caret always - i know i can just close the future pr that will come, but isn't in next run try to pin it again? or when new release of it it will send pr with pinned version?)_

**Comment by rarkins** [comment]
So you added config to package.json then installed Renovate App for the repo? And it raises unnecessary PR still?

**Comment by rarkins** [comment]
To target specific packages, add config like this:

```
"packageRules": [{
  "packageNames: ["semantic-release"],
  "pinVersions": false
}]
```

Note this used to be called "packages", now renamed to "packageRules". Both work, but don't use both at the same time.

**Comment by charlike** [comment]
Yea, look over here https://github.com/tunnckoCore/koa-better-serve/pull/6.

Actually, not sure what is the exact case. Maybe is interesting, because PR is sent 5 minutes after the commit that has the config, the old one package.json didn't have renovate field.

**BUT**, there's but. Because Renovate is activated only on @tunnckoCore, before some time (dont know how much, but in around last hour +/- some mins) i moved it there from @charlike profile (so it's activated on that moment). So maybe that's the reason.

So yea, maybe my fault. I will probably do more moves today, so we'll see if there is really a problem.

**Comment by charlike** [comment]
> To target specific packages, add config like this:

Cool! Thanks :blossom:

**Comment by rarkins** [comment]
You can always just close the PR I merged and it will then use package json config if found. But I'll keep this open to investigate if we can prevent this in the first place.

**Comment by rarkins** [comment]
Renovate runs on hourly schedule still so any "5 minutes after" is purely coincidental.

**Comment by charlike** [comment]
> Renovate runs on hourly schedule still so any "5 minutes after" is purely coincidental.

Yea, yea, probably that's what happened. Because in the moment when it was activated (in the moment of move) there was the old package.json :)

**Comment by rarkins** [comment]
BTW Renovate only looks for either Configure Renovate PR or `renovate.json` so this behaviour is expected. But it's probably OK to also look for a renovate config in root `package.json` too.

**Comment by charlike** [comment]
If i close its the Configure PR, does it will run next time? huh, what stupid question ;d

**Comment by rarkins** [comment]
Yes it runs if it finds any closed configure PR

**Comment by charlike** [comment]
Don't know, look carefully the numbers and my clock:

![2017-08-06-14 58 34_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/29003010-8827b05c-7ab7-11e7-8365-2ad508a82a1c.png)
![2017-08-06-14 58 26_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/29003011-88408636-7ab7-11e7-81bd-fa1656f3bc5f.png)


There are no new PRs. Am i crazy, or today is just very bad day for me :sob: :scream:

**Comment by rarkins** [comment]
But why are you expecting any PRs for that repo? With the default settings (in Configure Renovate PR) there was just one PR expected - pinning `semantic-release`. But then in your `package.json` you've unpinned that package so therefore.. nothing to do?

**Comment by charlike** [comment]
Oh god, yea, sorry!  :D Awful day.

I'll close it, and will see if it happens to some other repos :)
