### ISSUE TITLE
Support global config (preset)

### ISSUE THREAD

**Issue by ikatyang** [singapore/renovate#646]
I'd like to have a global config (preset) for my all renovated repos, since I have to manually set `prCreation` to `"no-pending"` for all of my repos due to the new feature `unpublishSafe` or something else that'll turn on by default in the future.

Maybe we can have some preset package/git-repo so that renovate can pick up the preset then override them using local configs.

Suggested config may look something like:

(renovate.json)

```json5
{
  // using node module resolution
  // const presetConfig = require('my-preset-package');
  "preset": "my-preset-package"
  // ...
}
```

**Comment by rarkins** [comment]
This is in late stages of planning already :)
Term will be "presets" and work similarly to eslint shareable configs. I'll describe here soon.

**Comment by rarkins** [comment]
Will work from #647
