### ISSUE TITLE
Override semantic commit detection

### ISSUE THREAD

**Issue by SpainTrain** [singapore/renovate#656]
Based on behavior we are seeing and https://github.com/singapore/renovate/commit/f8ec742b3b6cbc0cca5bef539813299489d1527e#diff-73688046bb9115014ff862983588884dR91 , it doesn't appear there is a way to override the semantic commit detection with a config setting.  If this isn't correct, LMK.

If correct, it would be great to have a way to do it.  We have repos that are not npm modules (webapps, etc.) that have semantic commits in their history (mostly due to previously using GK).  Semantic commits don't really make sense in these repos and violate the commit convention in use.  

BTW, because our convention uses emoji, the atom commit convention would probably resolve this issue - https://github.com/singapore/renovate/issues/464

**Comment by SpainTrain** [comment]
Should also note I am happy to work up a PR if this sounds like a reasonable config option and there is an approved approach.

**Comment by rarkins** [comment]
Hi @SpainTrain sorry the delay. I actually looked into this and typed out a reply right away but for some reason it was not sent or received here.

Old behaviour:
- We check for any semantic commit prefix history during onboarding and suggest `semanticCommits: true` so

New behaviour:
- We check for any semantic commit prefix history *every run* and implicitly turn it on if found
- It can still be overridden if you add `semanticCommits: false` to your renovate config

I tested this out quickly with one of my test repositories that had a history of semantic commit messages. When I added the false setting to renovate.json, the next PR was without the semantic prefix, so I think this feature is working as expected and no PR/change necessary.

**Comment by SpainTrain** [comment]
Ok, so this needs to be turned off per-repo?  In our Heroku env we currently have it turned off in global config: 

![selection_583](https://user-images.githubusercontent.com/380032/29183920-62324786-7dd2-11e7-94f9-85737d5e06da.png)

**Comment by rarkins** [comment]
Good question. I think I can work out a solution for you that doesn't require per-repo config. The dynamic detection would be overriding the default config (false) and your global config (false) and then any repo config would override that. 

Instead it should be possible to default semanticCommits to null or undefined and do dynamic detection only if the global config remains as null. Ie do not dynamically detect if it's been configured statically in globals beforehand. 

You are welcome to submit a PR but I should be able to fix it within a few days if not.
