### ISSUE TITLE
Add link to github repo

### ISSUE THREAD

**Issue by charlike** [singapore/renovate#660]
Heya, can you please add link to the github repo in the main navigation of the site? probably on the left side of the `DOCS` link.

I often click my badge that intentionally links to the site, then i scroll to the bottom to click the `source` link at the footer. ;d

It's stylistic thing, i know. I know that i can create some shortcut or bookmark, but 1) don't have place for bookmarks as you look deeply on the screenshots that i was giving, 2) my keyboard is full of shortcuts too, 3) won't be using it so much in the future, but know i scroll there for some things i also scroll the repo for other things.

**Comment by rarkins** [comment]
I'll think of how to add it. Perhaps a GitHub icon on the top row would work. I never liked those "Fork me on GitHub" ribbons - confusing for the 99% of people who'd be happy using software but no intention of forking it

**Comment by charlike** [comment]
it's not needed to be ribbon, didn't even though for it ;d link in the menu "Source" would be enough.
