### ISSUE TITLE
Does not send updates

### ISSUE THREAD

**Issue by charlike** [singapore/renovate#669]
Veeeery strange. I have this one package https://github.com/tunnckoCore/hela, that is used in another @tunnckoCore repos, basically exposes few tasks that is used in npm scripts. I has `rollup` as dependency. But it seems that it didn't send updates when rollup get 0.47.x versions. Last update that is done is to `0.46.2`, before i slept last night.

Schedule is configure to be per 15 minutes, intentionally & temporary, i'm just testing some things and want to see changes very fast.

Any ideas? Could it be because too much checks in this 24 hour period? The rate limits?

**Comment by rarkins** [comment]
You can't set a schedule faster than every hour, so this is actually invalid:
```
"schedule": [
    "every 15 mins every weekday"
  ],
```

From the docs:
> Renovate itself will run as often as its administrator has configured it (e.g. hourly, daily, etc). But you may wish to update certain repositories less often, or even specific packages at a different schedule.

and

> you can define days of week or hours of the day in which renovate will make changes. 

As a result, I'm seeing this in my logs:
```
    "repository": "tunnckoCore/hela",
    "branch": "renovate/rollup-0.x",
    "level": 30,
    "msg": "Skipping branch as it is not scheduled",
```

#550 is an open issue to improve schedule validating.

**Comment by charlike** [comment]
> You can't set a schedule faster than every hour

That's absolutely not true. It happened few times, so it is working, or it _was_ until these too much updates.

Both quotes doesn't say that you _can't_ set it to be faster than hour, they only say that it can be configured, but not that that it's kinda _forbidden_ to set it less than hour. As about the sentence, it's correct and is supported by the `later`.

Anyway, okey, no problem. The docs probably should be updated too.
