### ISSUE TITLE
Automerge for lockfile maintenance

### ISSUE THREAD

**Issue by ikatyang** [singapore/renovate#706]
It seems currently `automerge` does not support lockfile maintenance, it'd be better to have it since it's annoying to merge them all manually, and it's a good way to find out if there are problems from deep dependencies.

suggested option:

- an option `automerge: boolean` in `lockFileMaintenance `
- or expand `automerge` to be something like `automerge: ['minor', 'lockfile-maintenance']`

EDIT:

Based on <https://renovateapp.com/docs/configuration-reference/package-file#lockfilemaintenance>
> Renovate may run a few times within that time - even possibly updating the lock file more than once - but it hopefully leaves enough time for tests to run and automerge to apply, if configured.

Does that mean I have to set `automerge: 'any'` in `lockFileMaintenance`? 😱😱😱

**Comment by rarkins** [comment]
I need to check the logic to work out the best way to make this work. 

> an option `automerge: boolean` in `lockFileMaintenance`

I've been thinking whether to change the way `automerge` is configured to deprecate the `patch/minor/any` approach and instead use boolean nested inside config objects. So your suggestion would work with it.

> Does that mean I have to set `automerge: 'any'` in `lockFileMaintenance`? 😱😱😱

This might work.. but yes it sounds scary
