### ISSUE TITLE
Manual semantic commit enablement not working

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#715]
From @denkristoffer https://github.com/singapore/renovate/issues/473#issuecomment-323784995

> We haven't actually switched to using semantic commits ourselves yet, I was hoping to take the first step by using it with renovate 🙂 The latest PR from renovate is called "Update dependency to v0.0.6" – that's from 12 hours ago even though I added "semanticCommits": true more than two weeks ago.

**Comment by denkristoffer** [comment]
@rarkins This is probably due to https://github.com/singapore/renovate/issues/720#issuecomment-324216492 as well, don't you think? I'm sorry about that 🙁

**Comment by rarkins** [comment]
Yes, you're probably right. I'll close this but please reopen if you don't see it behaving as expected.
