### ISSUE TITLE
Automerge patch not working?

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#720]
Transferred from https://github.com/singapore/renovate/issues/473#issuecomment-323963896:

Another thing: `"automerge": "minor"` – shouldn't this automerge commits such as this one, instead of creating a PR?:

<img width="812" alt="screen shot 2017-08-22 at 10 38 01" src="https://user-images.githubusercontent.com/219017/29556423-1e12717c-8726-11e7-9c7b-7de0277e9451.png">

**Comment by rarkins** [comment]
I set up a test here: https://github.com/renovate-tests/automerge/pull/10 using your renovate.json config and travis-ci

It behaved as following:
- branch was created on run 1
- PR was not created on run 1 as prCreation is set to "not-pending"
- PR was created on run 2 after travis testing passed
- PR was not automerged on run 2 as Travis added a new status check for the PR
- PR was automerged on run 3 after travis went green again

@denkristoffer I notice in your repo that auth0-js is now up to 8.9.3. Did you merge that manually, or did renovate automerge it?

In your screenshot it shows 13 hours elapsed since the PR creation and still no automerge, so it looks like something was wrong. 

There's a reasonable chance that whatever was wrong was fixed in this commit this morning: https://github.com/singapore/renovate/commit/2ca2e7c8ca4f1a830dc29150941d022e1f34a407

**Comment by denkristoffer** [comment]
I merged it manually. I keep an eye on whether the commit this morning changed anything from here on.

**Comment by rarkins** [comment]
Ok, please reopen this issue if you find it happening again

**Comment by denkristoffer** [comment]
It's happening again 🙂 

> This Pull Request updates dependency @​storybook/react](https://github.com/storybooks/storybook) from v3.2.5 to v3.2.6

I've left it unmerged.

**Comment by rarkins** [comment]
I think it's a config problem. I'm seeing:
```
"branch":"renovate/@storybook/react-3.x","level":30,"msg":"Pull Request #154 does not need updating"
"branch":"renovate/@storybook/react-3.x","level":20,"msg":"Checking #154 for automerge"
"branch":"renovate/@storybook/react-3.x","level":20,"msg":"No automerge"
```

I also found these log messages:
```
"msg":"No renovate.json found"
msg: "Detected 2 package files: packages/website/package.json,package.json"
"packageFile":"packages/website/package.json","msg":"No renovate config"
"packageFile":"package.json","msg":"Found package.json renovate config"
"packageFile":"packages/website/package.json","depType":"devDependencies","dependency":"@storybook/react"
```

It looks like you have 2 package.json files but the config is in only one of them. Therefore any config you specify will be applied only to packages in that package.json and not to the other one. In theory we might be able to add some "overrideRepoConfig: true" option in future that lets one package.json specify the behaviour for all package files, but that's not supported today. You will need to either copy/paste the config into the second package.json, or into a renovate.json file in the root of the repo.

**Comment by denkristoffer** [comment]
Oh indeed, the renovate config is only in my root package.json, I just assumed that it would apply to the whole repository when placed there. I'll add the config to the different packages and see if that fixes it 👍
