### ISSUE TITLE
Suggestion about auto merging / assigning and etc

### ISSUE THREAD

**Issue by charlike** [singapore/renovate#722]
Hay there! :)

I'm thinking that it would be good if we can customize options a bit more. For some weeks i'm wanting both 1) Renovate to open PRs even if build pass and 2) want to assign me, so it will be shown in the notifications (as like someone mentioned me, not just notification because i'm watching the repository). But here's the problem: i don't care if build pass and don't want noise.

So, fix for this case would be to open PRs , but assign me only if the build fail, so i will go and look what's happening.

Currently, i'm using `branch-push` only because don't care about passing builds, but i want to see the PRs and so others to be able to see that PRs, not just some commits by some bot. I want users to see that other bots (such as codecov comments) and services (such as travis and nodesecurity) pass. Actually, this review process is available in the commit history with green tick, but you should click that tick and it's not so obvious and no so easy to see what passed and etc.

**Comment by rarkins** [comment]
Please confirm if I'm understanding:

1. You want PRs for everything
2. You want to automerge any that pass
3. You want to assign PRs to yourself only if they fail?

**Comment by charlike** [comment]
> You want PRs for everything

Yes, as like with `pr` option.

**Comment by rarkins** [comment]
Right now our functionality is "only assign PRs if automerge is disabled". I guess you want "only assign PRa if automerge is disabled or tests fail"?

**Comment by charlike** [comment]
> Right now our functionality is "only assign PRs if automerge is disabled"

That's definitely not true. I had automerge enabled and `automerType: pr` and it was assigning me :P I'll try to find that prs

I want to automerge prs, but assign me only if tests fail.

**Comment by charlike** [comment]
like

```json
{
  "automerge": true,
  "automergeType": "pr",
  "assign": ["charlike"]
}
```

**Comment by charlike** [comment]
Hm, okey, my fault, it didn't assign me. :) But yea, you get what i want?

**Comment by rarkins** [comment]
I'm fine with updating existing logic to assign PRs if tests fail. The only thing is that if you unassigned yourself then it will probably reassign you each time. GitHub doesn't expose the history of assign/unassign so we can't tell.

**Comment by charlike** [comment]
> if you unassigned yourself then it will probably reassign you each time

Do you mean in each commit of that pr? If so, i don't think it would be a problem, because you are working on that to fix that pr, so you are there anyway.
