### ISSUE TITLE
Automerge seems broken

### ISSUE THREAD

**Issue by ikatyang** [singapore/renovate#732]
See [`is:pr user:ikatyang author:app/renovate created:2017-08-25T00:00:00+08:00..2017-08-25T08:00:00+08:00 `](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+user%3Aikatyang+author%3Aapp%2Frenovate+created%3A2017-08-25T00%3A00%3A00%2B08%3A00..2017-08-25T08%3A00%3A00%2B08%3A00), they are all patch-level updates.

It worked fine yesterday, I guess #728 somehow broke the automerge.

**Comment by rarkins** [comment]
Thanks. I think that the migration script for automerge is somehow not functioning correctly. I'll look at it now.
