### ISSUE TITLE
Overrides renovate.json on onboarding MR w/ GitLab API v4 (GitLab CE 9.3.5 0c9ceb3)

### ISSUE THREAD

**Issue by dherges** [singapore/renovate#757]
Configured and ran renovate to update projects on a self-hosted GitLab CE. Renovate is running w/ a personal access token from my account, thus commits made by renovate show up w/ my persoanl profile picture.

Renovate created the initial onboarding merge request (first commit).

Me then edited renovate.json on the branch (second commit).

Renovate then ran again and did override the renovate.json again (third commit, second picture).

![2017-08-31 15_18_38-configure renovate 193 merge requests orbis-u _ u-client-framework gitl](https://user-images.githubusercontent.com/901354/29925226-ea5868d2-8e5f-11e7-8224-d2f5460069ec.png)

![2017-08-31 15_19_25-add renovate json de8c58a9 commits orbis-u _ u-client-framework gitlab](https://user-images.githubusercontent.com/901354/29925229-ec87b73e-8e5f-11e7-9bfc-229cd7e1ab0c.png)

Why did that happen? Is that configurable behaviour? Is my configuration wrong? Is it a bug?

The `config.js` for renovate is minimalistic:

```js
module.exports = {
    platform: 'gitlab',
    endpoint: 'https://GITLAB_CE_935/api/v4',
    token: 'PERSONAL ACCESS TOKEN',
    onboarding: true,
    timezone: 'Europe/Amsterdam',
    logLevel: 'trace',
    repositories: [
        '184' // <-- had to put project ids instead of project names here (for whatever reason)
    ],
    semanticCommits: true,
    semanticPrefix: 'chore',
    labels: ['renovate']
};
```

**Comment by rarkins** [comment]
Yes it happens if you use the same user to edit the file as Renovate is using. Renovate:

- uses the the account id to determine if commits were made by it or not
- assumes any commits you made with the same user account must be its own
- retains control of the renovate json and keeps it "current" until anyone else starts editing the branch

The result is what you saw - it will override any changes you make to renovate json using the same account.

**Comment by dherges** [comment]
Ok, so using a dedicated account for renovate should fix this?

Oh, and ultra-fast cool response time! :rocket: :steam_locomotive:

**Comment by rarkins** [comment]
Yes, a dedicated account is definitely recommended as it also makes it easier to distinguish between when the bot did something (eg close or merge a PR) versus when you did. I'll leave this issue open as a reminder to improve the docs on this topic
