### ISSUE TITLE
Private registry lookup failing for repo-hosted .npmrc

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#763]
Raised by @dherges in https://github.com/singapore/renovate/pull/309/files#r136535783

**Comment by rarkins** [comment]
From @dherges :

@rarkins This line does not work w/ a private npm registry when the `.npmrc` is read from target repository.  Example:

```
npmrc = { registry: 'https://my.corporate.local/npm-private/' }
regUrl = https://registry.npmjs.org/
pkgUrl = https://registry.npmjs.org/sort-object
```

It looks like [registry-url does not read that second paramter](https://github.com/sindresorhus/registry-url/blob/master/index.js)

The private npm registry does work, when I put the .npmrc file to the renovate deployment folder, i.e.:

```
|- node_modules
   |- .bin/renovate
|- .npmrc
```

**Comment by rarkins** [comment]
From @dherges:

When read from that second `.npmrc`, the url is constructed right:

```
regUrl https://my.corporate.local/npm-private/
pkgUrl https://my.corporate.local/npm-private/sort-object
{ registry: 'https://my.corporate.local/npm-private/' }
```

It works when there are no private packages references. When renovate tries to read npm packages that are only available on the private registry, it errors.

**Comment by dherges** [comment]
I summarize again:


Code in question: https://github.com/singapore/renovate/blob/master/lib/api/npm.js#L30-L34

```js
const regUrl = registryUrl(scope, { npmrc });
```

`regUrl` does not work w/ a private npm registry when the `.npmrc` is read from target repository.

```
DEBUG: Found .npmrc file in repository (repository=my-project-name)
```


#### Example

```
npmrc = { registry: 'https://my.corporate.local/npm-private/' }
regUrl = https://registry.npmjs.org/
pkgUrl = https://registry.npmjs.org/sort-object
```


It looks like [registry-url does not read that second paramter](https://github.com/sindresorhus/registry-url/blob/master/index.js)


#### "Counter Example"

The private npm registry does work, when the .npmrc file to the renovate deployment folder, i.e.:

```
|- node_modules
   |- .bin/renovate
|- .npmrc
```

Here, `registry-url` picks up the private npm registry url from the `.npmrc` file.

**Comment by rarkins** [comment]
So the the use specific use case that's not working is:

- Custom registry is being used for all packages (https://my.corporate.local/npm-private/)
- `.npmrc` is checked into relevant repos, it contains: `{ registry: 'https://my.corporate.local/npm-private/' }`
- Renovate is incorrectly querying `https://registry.npmjs.org` instead of `https://my.corporate.local/npm-private/`

This use case can be made to work if the same `.npmrc` is added to the machine that Renovate is running from.

My initial root cause:
- `registry-url` completely ignores the second parameter we're passing, so that part is clearly incorrect on our part
- `registry-url` is basically just requiring `npm` to leverage its "npmrc hunting" and that's why when the npmrc is on the Renovate server it works

Solutions:
- Stop passing npmrc to registry url as it won't do anything with it anyway
- We need to do one of these two options:
   * Write the `.npmrc` to disk in a location where `npm` will find it when it's required (basically the current working dir or higher up)
   * Parse the npmrc ourselves for registry/scope. But then probably the authentication part will fail anyway

**Comment by rarkins** [comment]
Here is the other - related - library we are using: https://github.com/rexxars/registry-auth-token. It seems to support npmrc as a parameter in its usage examples:

```
// Use the npm config that is passed in
console.log(getRegistryUrl('http://registry.foobar.eu/', {
  npmrc: {
    'registry': 'http://registry.foobar.eu/',
    '//registry.foobar.eu/:_authToken': 'qar'
  }
}))
```

I wonder if we can use that library for both purposes (obtaining URL as well as obtaining token). I'm also aware/concerned about someone having multiple `.npmrc` files for different `package.json` files in their repo and how to handle that. I may need to defer that to later if it's too hard to solve now.

**Comment by rarkins** [comment]
@dherges I'm guessing for your specific use case that you don't use/need *authentication* for your local npm registry? i.e. as soon as the registry URL is correct, it would work?

I'd also like to consider/test the case of a private registry that requires authentication, e.g. npmrc includes a token too.

**Comment by dherges** [comment]
Yes. We *DO NOT* need authentication when *reading* from the npm registry, as renovate does.

We do need authentication when publishing to the npm registry, which renovate does not do.

Configuring the private registry on the deployment machine (where renovate is run from) is not a viable solutions, since we're running proxies of the npm registry for different (physical) locations and some teams put a `.npmrc` file in their repository. So renovate will pick up a different registry url than the humans do and we will likely have lots of lockfile changes. Imho, the user `.npmrc` from target repository should override the renovate `.npmrc` from deployment machine.

**Comment by rarkins** [comment]
Yes I agree - repository npmrc should override Renovate server npmrc. BTW it's also possible to configure npmrc as a strong in renovate config too, but that's probably not applicable to your situation, nor does it fix the bug either. Please check out the PR fix when you get time.

**Comment by dherges** [comment]
Hmpf, the onboarding now works! However, for the merge requests it now fails when creating the commit:

```
DEBUG: Writing repo .npmrc (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: Writing package.json to /tmp/tmp-18512AtbY7bEtT1Zy (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: Writing .npmrc to /tmp/tmp-18512AtbY7bEtT1Zy (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: Removing any previous lock files (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: Writing any updated package files (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: Writing package.json (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: Generating yarn.lock for . (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: Generating new yarn.lock file (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: Spawning yarn install to create /tmp/tmp-18512AtbY7bEtT1Zy/yarn.lock (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: yarn stdout:
        (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
DEBUG: yarn stderr:
       error An unexpected error occurred: "https://registry.yarnpkg.com/@internal%2finternal: Not found".
        (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
 WARN: yarn install error (repository=184, dependencies=typescript, branch=renovate/typescript-2.x)
       "err": {
         "errno": -2,
         "code": "ENOENT",
         "syscall": "open",
         "path": "/tmp/tmp-18512AtbY7bEtT1Zy/yarn.lock"
       },
       "stdout": "",
       "stderr": "error An unexpected error occurred: \"https://registry.yarnpkg.com/@internal%2finternal: Not found\".\n"
```

Guess the resulting `.npmrc` (which is possibly a merged one) needs to be copied to the tmp folders.

But that looks good!

```
$ cat /tmp/tmp-18378Gqm4ZkeyTYye/.npmrc
registry=https://my.corporate.local/npm-private/
```

Also, running `yarn install` manually in that tmp folder succeeds.

Maybe, yarn does not pick up the `.npmrc` file when launcched like this?!?

https://github.com/singapore/renovate/blob/ea9ace2a76a1843473c92dbc8330b9c96cd27f26/lib/workers/branch/yarn.js#L16-L31

**Comment by rarkins** [comment]
Fastest thing to try would be to copy the yarn binary to that tmpDir and execute it from there instead of the original path to see if it picks up the npmrc then. It may be looking only in its own path and up

**Comment by rarkins** [comment]
I'm away from my computer for a few hours at least so can't test that right now. Should need only one fs line to copy yarn plus change the spawnSync options to remove extra path, in case you can try yourself.

**Comment by dherges** [comment]
Pretty much solves it:

```bash
$ pwd
/tmp/tmp-18378Gqm4ZkeyTYye
$ cp /srv/renovate/renovate-u/node_modules/renovate/bin/yarn-0.27.5.js 
$ ./yarn-0.27.5.js
yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
warning validate-commit-msg@2.14.0: Check out CommitLint which provides the same functionality with a more user-focused experience.
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning browser-sync > browser-sync-ui > weinre > express@2.5.11: express 2.x series is deprecated
warning browser-sync > browser-sync-ui > weinre > express > connect@1.9.2: connect 1.x series is deprecated
warning istanbul-combine > istanbul > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to
find it in the tree.
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 102.56s.
```

I'll take a look! Don't worry and hurry! We Europeans start weekend in ~1 hour!

**Comment by rarkins** [comment]
FYI, I tested with yarn v1.0.1 and same problem occurs

**Comment by rarkins** [comment]
I'm testing using a kind of "opposite" approach to what you're doing. I add a valid (npm) package to `package.json` and then set `.npmrc` to point to an invalid registry. Therefore I want it to try the invalid registry and *fail*.

Set registry to google.com:
```
$ cat /tmp/test2/.npmrc
registry=https://google.com
```

Write a short js script that requires the repository's yarn helper js:
```
const yarn = require('/Users/rhys/github/renovate/dist/workers/branch/yarn');

const logger = {
  debug: console.log,
  warn: console.log
};

const lockFile = yarn.generateLockFile('/tmp/test2', logger);
console.log(lockFile);
```

.. and it fails, as I expect. i.e. in this case `yarn` *is* honouring the registry setting yet somehow when run through Renovate it is not?

**Comment by dherges** [comment]
It must be because of the child process?!? That's my current thinking...

Can you re-produce by starting yarn in a subshell? Somehow like `$(cd /tmp/dir && yarn)` maybe?!?!

**Comment by rarkins** [comment]
@dherges but isn't my last example using the same child process? It requires the yarn helper file directly from the repo so I expected it to behave the same, yet it seemed to honour the registry= setting in the `.npmrc`. My best guess now is they Renovate is somehow setting some env variable that is altering yarn's behaviour. But I have doubts on that guess too. Ideally we could have a way to reproduce this simpler than having to run Renovate against real repos.

**Comment by rarkins** [comment]
@dherges I've made some changes to how `yarn` is called, can you try with the latest version? Now using `yarn` directly out of `node_modules` plus passing empty `env`.

**Comment by dherges** [comment]
With the `9.61.11` version renovate creates merge request.

Repo-hosted `.npmrc` file is being recognized!

**Comment by rarkins** [comment]
Awesome! Closing this issue then
