### ISSUE TITLE
Yarn workspaces: look inside package.json files for package names to ignore

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#781]
Example repo: https://github.com/tunnckoCore/elmaz
Cc @charlike

It produces server-side warnings like this:
```
    "repository": "tunnckoCore/elmaz",
    "packageFile": "packages/create-actor/package.json",
    "depType": "dependencies",
    "dependency": "@elmaz/emitter",
    "msg": "Failed to look up dependency",
```

This "missing" package can actually be found here: https://github.com/tunnckoCore/elmaz/blob/master/packages/emitter/package.json#L2

It looks like the only way to know to ignore this dependency is:

1. Trigger behaviour based on "workspaces" field in root `package.json` (we already do this)
2. For each `package.json` inside the workspaces packages directory, read the `package.json` (we already do this too)
3. Add each module name to our ignored list and do not attempt to renovate (we do not do this. currently we just use the directory name)

**Comment by charlike** [comment]
Don't know. It's not a problem. I will publish it soon, just trying the workspaces for the first time and playing with some Elm-like ideas/implementations..

I don't you need a fix. In most cases packages will be published.

**Comment by rarkins** [comment]
Yeah, it's not really a big issue.

1. If packages are published then usually they should always be up to the latest anyway. i.e. Renovate's lookup will never return upgrades available

2. Unpublished packages will fail the lookup and generate this warning, but they won't cause any lock file generation to fail, because `yarn` will figure that part out

3. If the directory name is the same as the package name, this problem won't happen at all
