### ISSUE TITLE
Add support for npm dependencies for Meteor build packages (package.js files)

### ISSUE THREAD

**Issue by Urigo** [singapore/renovate#785]
Most Meteor applications today install npm packages just like any other Node app, using package.json with npm or yarn.

But if a Meteor build package depends on Npm, it has it specified inside the `package.js` file using the `Npm.depends` function.
The format of the input of that package is identical to package.json.

Adding support for tracking npm dependencies for Meteor's `Npm.depends` would be very cool :) 

Here are few examples:
1.  https://github.com/RocketChat/Rocket.Chat/blob/e8074d22b6acdcbd61030d52754340f56ff98148/packages/meteor-accounts-saml/package.js#L19-L26
2. https://github.com/RocketChat/Rocket.Chat/blob/fb58699191e823f472efee987938ec1ac662fb72/packages/rocketchat-theme/package.js#L45-L48

It can have all types of URLs that npm supports such as git URLs
[Reference](https://docs.meteor.com/api/packagejs.html#PackageNpm-depends)

The only difference is that it supports only exact version numbers, not including `^`.

**Comment by rarkins** [comment]
Can you point me to one or more public examples? Enough to cover all use cases

**Comment by Urigo** [comment]
@rarkins oops how did I forget that :)  added to the main comment

**Comment by Urigo** [comment]
@rarkins made more changes to the comment

**Comment by rarkins** [comment]
Are `package.js` files only found at root of a repo or can they be nested? (Eg inside monorepo)

**Comment by rarkins** [comment]
I think there will be a lot of false positive `package.js` files found in repos, although I suppose that `NPM.depends` is distinctive enough that we shouldn't fine any false positives of that in non-meteor repositories. 

Does the `package.js` file have any formatting conventions by any chance? E.g. 2 spaces? How about single vs double quotes?

Assuming not, it will be a little challenging to modify the dependencies in a way that doesn't reformat the rest of the file. Actually, detecting them to begin with could be challenging too, if there is no convention for the JS formatting. Probably needs an AST parser to substitute for the JSON.parse we use for JSON.

**Comment by Urigo** [comment]
@rarkins they can also be nested.

there is no formatting conventions and now I see your point and yes, it can be more challenging than parsing a JSON.....

**Comment by rarkins** [comment]
I can't access the Example link. Is it a typo or private repo?

**Comment by Urigo** [comment]
I've updated the links

**Comment by rarkins** [comment]
This looks useful in terms of parsing-editing-writing the file while retaining as much formatting as possible: https://github.com/benjamn/recast/blob/master/README.md

**Comment by rarkins** [comment]
@Urigo this feature is now ready for testing in #786. I've tested it locally only against a copy of https://github.com/RocketChat/Rocket.Chat so far and it works as I'd expect. Can you suggest some additional repositories to test against before I merge?

**Comment by Urigo** [comment]
ok!  after a lot of unrelated cleanups, I've merged renovate to the [Angular Meteor repo](https://github.com/Urigo/angular-meteor/pull/1642)!
@rarkins first of all thank you !
second, I hope I've done it right, at the beginning it gave me [this config](https://github.com/Urigo/angular-meteor/pull/1642/commits/4f1e90176ae74766e9d82e54c6761103e8c0639a) which I haven't found on the docs, so I've changed it to [this](https://github.com/Urigo/angular-meteor/pull/1642/commits/fcf93437b8ff964f3af3a6b43a312f3fa7db1759) and pushed.

**Comment by rarkins** [comment]
@Urigo I submitted a PR to fix the `renovate.json` :)

https://github.com/Urigo/angular-meteor/pull/1666

I'm actually about to flip the switch and make Meteor support enabled by default anyway, however you would still need to fix up the `renovate.json` config.

**Comment by rarkins** [comment]
@Urigo please also see #1008
