### ISSUE TITLE
.npmrc not being read (self-hosted)

### ISSUE THREAD

**Issue by IGZgustavomarin** [singapore/renovate#822]
I think that `renovate` process is not reading my `.npmrc`  file.  I'm getting this messages output from renovate:

```
DEBUG: Dependency not found: @maverick/validate-token (repository=services/account-service, packageFile=package.json, depType=dependencies, dependency=@maverick/validate-token)
       "err": {}
 INFO: Failed to look up dependency. This will block *all* dependencies from being updated due to presence of lock file. (repository=services/account-service, packageFile=package.json, depType=dependencies, dependency=@maverick/validate-token)
DEBUG: @maverick/validate-token lookup results (repository=services/account-service, packageFile=package.json, depType=dependencies, dependency=@maverick/validate-token)
       "results": [
         {
           "type": "warning",
           "message": "Failed to look up dependency. This will block *all* dependencies from being updated due to presence of lock file.",
           "repositoryUrl": null
         }
       ]
```
But I know that the packages exists and are accessible as the @maverick scope is setup on the `.npmrc`  and it works ok if I run `npm install @maverick/validate-token` on the same path that I ran renovate. 

Also, this was working fine before, I just found out today that my deps were not being updated if renovate founds this case. And we have lots of private deps like these.

**Comment by rarkins** [comment]
Can you attach or email me a zip if the full debug log? Need to confirm it's first detecting the npmrc and then second that it's using the values correctly

**Comment by rarkins** [comment]
It would also be helpful for me to understand the directory structure and npmrc content (feel free to anonymise it first)

**Comment by IGZgustavomarin** [comment]
I added the full log. Our repos don't have a `.npmrc` file versioned by git. We copy the file on our build process. So renovate has its own copy of `.npmrc` before running.  Does it help?

Also I'll try to run it with the new option `--npmrc` and see how it goes

**Comment by rarkins** [comment]
So the npmrc is in the same dir you run Renovate from?

**Comment by rarkins** [comment]
And yes you can possibly configure the npmrc content manually via cli or env to overcome this however it was not my intention to stop supporting actual .npmrc files in file system too.

**Comment by IGZgustavomarin** [comment]
> So the npmrc is in the same dir you run Renovate from?

Yes, it is in the same dir where renovate runs.

**Comment by rarkins** [comment]
Quickest approach would be to try to configure npmrc as env or cli then. Using something like `RENOVATE_NPMRC=$(cat .npmrc) renovate` might work? I'm on vacation this week and next and not getting a lot of keyboard time, sorry

**Comment by IGZgustavomarin** [comment]
I've ran it with `RENOVATE_NPMRC=$(cat .npmrc)` env variable, the `.npmrc` is ok and its in the path, but I'm getting the same results.

**Comment by IGZgustavomarin** [comment]
I found more info on this. It seems that there is an error thrown when the package metadata doesn't contain publication time information. 

This happens in our setup because we are using an old version of [verdaccio](https://github.com/verdaccio/verdaccio). That, together with [this change on renovate](https://github.com/singapore/renovate/blob/master/lib/api/npm.js#L84) that acces `res.body.time[version]` but `res.body.time` is undefined and throws an error.

I'll try to update our private npm setup and see if that fix the issue. But maybe the error message could be more informative, or you can add a check for missing `res.body.time` there.

**Comment by rarkins** [comment]
Thanks for debugging it further. We can probably add a fallback for that time field if you can't update. It's only used for checking if an update is > 24 hours old and can't be unpublished, but that's not a concern for private repos anyway.

**Comment by IGZgustavomarin** [comment]
That fallback would be helpul, thanks!

**Comment by rarkins** [comment]
Try using the latest patch and let me know how it goes

**Comment by IGZgustavomarin** [comment]
worked with latest version. Thanks
