### ISSUE TITLE
npm install error when trying to run renovate

### ISSUE THREAD

**Issue by Autre31415** [singapore/renovate#824]
On the latest release of renovate, at the `Spawning npm install to create /tmp/tmp-string/package-lock.json` step I'm getting this error:

```
module.js:471
           throw err;
           ^
       
       Error: Cannot find module '/home/renovate/node_modules/.bin/npm'
           at Function.Module._resolveFilename (module.js:469:15)
           at Function.Module._load (module.js:417:25)
           at Module.runMain (module.js:604:10)
           at run (bootstrap_node.js:389:7)
           at startup (bootstrap_node.js:149:9)
           at bootstrap_node.js:504:3
```

I believe it is due to this line here which is referencing the npm binary relatively from the directory the renovate command was executed in:

https://github.com/singapore/renovate/blob/f9b12dbb3eb95b06b4914feb692243dda75b1a40/lib/workers/branch/npm.js#L15

**Comment by rarkins** [comment]
Hmm that's true. I wanted to bundle yarn and npm to overcome versioning problems but need a way to reliably require it

**Comment by Autre31415** [comment]
I believe you can simply add npm as a dependency in package.json and require it that way

**Comment by rarkins** [comment]
Yes it's a listed dependency already which is then spawned. But I should derive the executable in a way that gives the correct absolute path.

**Comment by rarkins** [comment]
@Autre31415 can you try latest release and see if it's resolved?
