### ISSUE TITLE
add log message about which npm will be used

### ISSUE THREAD

**Issue by sky-code** [singapore/renovate#827]
add enabled by default logging  about which npm version will be used 
detect npm feature #825 already has logging, but log level is debug at this moment 
it would be good to have the same logging as at `npm` by default
as example:
```cmd
info using npm@5.3.0 (path)
info using node@v8.5.0 (path)
```

**Comment by rarkins** [comment]
This seems like "debug" info though, why do you want it at info level? I prefer to keep things that are only needed for troubleshooting out of info logs.

**Comment by sky-code** [comment]
different npm versions has different impact on `package-lock.json` file, because of that will be good to have info message about what npm version used by renovate.

**Comment by rarkins** [comment]
The version of non used is defined in the `package.json` dependencies

**Comment by rarkins** [comment]
https://github.com/singapore/renovate/blob/master/package.json#L66

**Comment by sky-code** [comment]
example from renovate default log:
```cmd
 INFO: Processing package file (repository=iCQR/natrix, packageFile=package.json)
```
but which npm is processing this file? this info have equal severity but one part now is debug and one is info.

**Comment by rarkins** [comment]
That package file is "processed" using internal Renovate logic and not by `npm` itself. `npm` is only ever called if generating a `package-lock.json`.

**Comment by sky-code** [comment]
> npm is only ever called if generating a package-lock.json.
and different npm version generate different package-lock.json but at this moment i don't know what npm used by renovate, because of it I suggest to print what npm will be used by renovate.
