### ISSUE TITLE
Urlencode filename for Gitlab

### ISSUE THREAD

**Issue by reicheltp** [singapore/renovate#849]
Using the following `renovate.json` file for a monorepo on gitlab.com:
```json
{
  "packageFiles": [
    "api.playground/package.json"
  ]
}
```

### Expected
renovate use the file `api.playground/package.json`

### BUT
I got the following error:
```
 WARN: package file not found (repository=my-monorepo, packageFile=api.playground/package.json)
 WARN: No package files found
```

### Workaround
Replace slash with `%2F` within the config file
```json
{
  "packageFiles": [
    "api.playground%2Fpackage.json"
  ]
}
```

**Comment by rarkins** [comment]
Thanks for the big report. URL encoding in GitLab has been a bit frustrating lately! I will fix this soon.
