### ISSUE TITLE
Update PRs out of schedule

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#879]
If users (a) define schedules for PRs, but (b) also require branches to be kept up-to-date with `master`, then currently that's a problem because branches will become stale and won't get updated until the next schedule window.

This feature proposes that branches get rebased out of schedule as default behaviour.

**Comment by rarkins** [comment]
For the same reasons, we may want to still automerge out of schedule too.

**Comment by mbrevda** [comment]
Also - delete merged branches

**Comment by rarkins** [comment]
@mbrevda I think Renovate should already delete merged branches out of schedule now anyway

**Comment by mbrevda** [comment]
I beg to differ

**Comment by mbrevda** [comment]
Just tested again. Ill PM you a link

**Comment by rarkins** [comment]
Rebasing has one big challenge - right now we don't *actually* rebase, i.e. we don't directly use the `git` command. Instead, we basically just regenerate the branch and swap it out with the old one. So this scenario would be challenging:

1. On monday, React 16.0.0 is released and a branch created
2. On tuesday, React 16.0.1 is released.. not updated due to out of schedule
3. On wednesday, `master` is updated with a commit

Expected scenario: The existing branch is rebased with React 16.0.0, not 16.0.1

Right now that's quite different to how Renovate's logic works. We'd need a way to detect and apply only the changes from the existing branch and not the latest available updates.

**Comment by rarkins** [comment]
This could be easily implemented at first if we allow new updates to be swept up with a rebase. i.e.

- Only **create** branches during schedule
- If a branch already exists, and is set for rebasing when stale, and it becomes stale.. update it with whatever is the current/latest for that branch

i.e. you'd get React 16.0.1 in the above-described scenario.

We also need to consider the scenario where a branch is created in schedule with prCreation=not-pending, and the tests finish outside of schedule. I think we should still create the PR then.

**Comment by rarkins** [comment]
To implement fully:

1. Retrieve existing `package.json`
2. Retrieve `package.json` from the parent `master` commit for that branch
3. Compare dependencies between them
4. Reapply the same changes against the latest `master`

**Comment by rarkins** [comment]
@brevda I checked the logs and found the cause:

1. dependency a is updated on a schedule
2. version 0.5.4 was raised as a PR during schedule
3. version 0.5.5 was released after schedule, so no update made
4. version 0.5.4 PR was merged and the branch left in place (`renovate/a-0.x`)
5. renovate does not delete `renovate/a-0.x` because it thinks that branch "should exist"

If 0.5.5 didn't exist at the time of merging then the branch would have been deleted.

But yes, this is related to this topic of "what should we do out of schedule?" and could/should be fixed.

**Comment by rarkins** [comment]
First iteration:

1. Do not create branches out of schedule. If schedule is not met, then skip
   - Unless it's a rollback?
2. Do everything else even if it's out of schedule
   * Update versions in branch
   * Rebase branches
   * Create PRs (e.g. if statuses turned green)
   * Automerge

Second iteration:

1. Don't update versions in branch unless schedule is met, but do everything else
