### ISSUE TITLE
Not running today (Wednesday) without schedule config

### ISSUE THREAD

**Issue by IGZgustavomarin** [singapore/renovate#885]
I run a `renovate` process twice a week. But at some point it stopped running. After checking the logs I found this message: 

```
DEBUG: Checking schedule "before 5am on monday" (repository=services/backoffice-service, dependencies=request,nock,mocha,eslint-plugin-node,eslint,mongoose,aws-sdk,@maverick/service-client,@maverick/openplatform-sdk, branch=renovate/all)
       "parsedSchedule": {"schedules": [{"t_b": [18000], "d": [2]}], "exceptions": [], "error": -1}
DEBUG: schedule.d (repository=services/backoffice-service, dependencies=request,nock,mocha,eslint-plugin-node,eslint,mongoose,aws-sdk,@maverick/service-client,@maverick/openplatform-sdk, branch=renovate/all)
       "schedule_d": [2]
DEBUG: scheduledDays (repository=services/backoffice-service, dependencies=request,nock,mocha,eslint-plugin-node,eslint,mongoose,aws-sdk,@maverick/service-client,@maverick/openplatform-sdk, branch=renovate/all)
       "scheduledDays": ["Monday"]
DEBUG: Does not match schedule because Wednesday is not in Monday (repository=services/backoffice-service, dependencies=request,nock,mocha,eslint-plugin-node,eslint,mongoose,aws-sdk,@maverick/service-client,@maverick/openplatform-sdk, branch=renovate/all)
DEBUG: Package not scheduled (repository=services/backoffice-service, dependencies=request,nock,mocha,eslint-plugin-node,eslint,mongoose,aws-sdk,@maverick/service-client,@maverick/openplatform-sdk, branch=renovate/all)
```
My config has no reference to any schedule: 
```
module.exports = {
  platform: 'gitlab',
  endpoint: 'https://gitlab/api/v3',
  onboarding: false,
  assignees: [ 8 ], 
  logLevel: 'debug',
  labels: ['upgrade'],
  ignoreDeps: [ /* ... */ ],
  repositories: [
     // just an array of repo names
     //  ... repo1, repo2, etc
  ]
} 
```

I did a quick check and removing the check `isScheduledNow` on [`workers/branc/index.js#31`](https://github.com/singapore/renovate/blob/master/lib/workers/branch/index.js#L31) solves my problem. 

Is there something wrong with my config? I have the latest version, but didn't change anything in the config since long time.

**Comment by rarkins** [comment]
Sorry for the inconvenience. I am not sure which logic change might have caused this, but I am pretty sure I can guess what's happening. "before 5am on monday" is the default schedule for lock file maintenance, and lock file maintenance is enabled by default. If you are using the "all" groupName to group all branches together then I think it's combining lock file maintenance and then that schedule gets used.

I think can quickly work around this by adding this to your config:
```
  "extends": [":maintainLockFilesDisabled"]
```

This will disable lock file maintenance to prevent it being grouped together (which would make no sense).

If that fixes it, please don't close this issue though. I'd like to add some code to prevent it happening without requiring a config workaround..

**Comment by IGZgustavomarin** [comment]
I've tried that but I see the same logs.

**Comment by rarkins** [comment]
If you can email me the full debug log, that will probably help. Additionally:

1. Is there any particular reason why you are using the apiv3 endpoint? I thought GitLab have deprecated it now and I plan to deprecate it in Renovate soon too.
2. I think your config you pasted here is perhaps incomplete? There is no reference to groupName "all" in the config, yet your dependencies are all grouped to `renovate/all`

**Comment by rarkins** [comment]
FYi I have a fix in https://github.com/singapore/renovate/pull/890 ready for merge soon

**Comment by IGZgustavomarin** [comment]
1. I've updated to latests Gitlab API v4. 
2. I think is grouped because I'm used `--group-name=all` on my npm script

I run it again but didn't create any new PR because today is not Monday. Do you see anything missing in my config?

**Comment by rarkins** [comment]
If it doesn't work with the latest release then please attach or send me the full debug log. I was able to reproduce same behaviour and fix today
