### ISSUE TITLE
No PRs raised recently in tunnckoCore org

### ISSUE THREAD

**Issue by charlike** [singapore/renovate#893]
dont what, but from few days it doesnt run. is it because the preserveSemverRanges option that have? I dont think so, because it not run on older repos too. review the @tunnckoCore org for reference and investigation and how deps are connected

**Comment by charlike** [comment]
and one side q: does it matter the order of the things in extends and should I put :base at the end, after my preferences?

**Comment by rarkins** [comment]
It does run, and there are hundreds of lines in my logs for `tunnckoCore` repositories from last hour, for example. Can you give me something specific to look for?

Put your own presets *after* `:base` so that they override it if necessary.

**Comment by rarkins** [comment]
I'm seeing logs like this:
![image](https://user-images.githubusercontent.com/6311784/31270909-7d55e186-aa86-11e7-9688-bc7f24d795f3.png)

At first glance it doesn't look wrong, so do you have any specifics?

**Comment by charlike** [comment]
hm, strange. for example in hela should pr update hela-preset-tunnckocore?

and with "older repos" I mean check eslint-config-standard-tunnckocore - it is with old renovate config and at least it should get pr to update hela from v0.7.7 to v1?

**Comment by charlike** [comment]
I dont see any prs for days no matter of what the repo is and what the config is.

**Comment by rarkins** [comment]
OK, sounds like something may be up but I'm not sure what. The last PR was created 4 days ago, ut prior to that you didn't get too many per-day anyway:
![image](https://user-images.githubusercontent.com/6311784/31271452-d946f1e6-aa87-11e7-8090-f22f629d5fa9.png)

I'll look specifically in `hela` repo now.

**Comment by charlike** [comment]
now seen your img. charlike is pretty old I not touched soon, just moved to the org I seen these prs before some days or weeks. so you should check the others from my prev comment

**Comment by charlike** [comment]
yea, u can look for parse-function too it uses hela and the hela preset so renovate should send prs in  some minutes or hour

**Comment by rarkins** [comment]
I'm getting confused. Please give me:
(1) exact repo I should look at
(2) exact dependency name that should have been updated

**Comment by charlike** [comment]
I set the schedule option in hela explicitly, exactly cuz these delays

**Comment by charlike** [comment]
ok

**Comment by rarkins** [comment]
https://github.com/tunnckoCore/parse-function/blob/master/package.json has:
```
    "hela": "^1.1.1",
    "hela-preset-tunnckocore": "^0.5.15",
```

i.e. they are ranges. Further, latest hela on npmjs.com is 1.1.1 and hela-preset-tunnckocore is 0.5.18

So.. they are in the range and don't need upgrade. 

Next question is: should they be pinned?

renovate.json is:
```
{
  "extends": [
    "tunnckocore"
  ]
}
```

So we look up the package `renovate-config-tunnckocore`, which has this renovate config:

```
      "renovate-config": {
        "default": {
          "extends": [
            ":base",
            ":automergePr",
            ":automergeMinor",
            ":prNotPending",
            ":preserveSemverRanges"
          ],
          "labels": [
            "deps",
            "renovate"
          ],
          "assignees": [
            "charlike"
          ],
          "ignoreDeps": [
            "semantic-release"
          ],
          "pinVersions": false,
          "rebaseStalePrs": true,
          "semanticCommits": true
        }
      },
```

i.e.

>  "pinVersions": false,

So there is no problem here that I can see:

1. You have configured a preset that sets version pinning to false, so Renovate will keep semver ranges
2. Your hela* devDependencies are in-range so don't need updates

Final question is: Is this how you intended it? Assuming not.. we should (a) fix it, and (b) work out if Renovate docs or preset behaviour should be behaved in any way to save someone in future form same problem.

**Comment by rarkins** [comment]
BTW the `pinVersions=false` config is kind of redundant anyway because you also added the preset `:preserveSemverRanges`:

```
 "preserveSemverRanges": {
      "description": "Preserve (but continue to upgrade) any existing semver ranges",
      "pinVersions": false
    },
```

But considering you configured to preserve ranges *twice*, I'm doubting it could be an accident.. which asks the question: why did you think Renovate should update `hela` if it's within range and you selected to preserve ranges? 

BTW you have a `yarn.lock` in that repo though, so that means that although you have ranges in `package.json`, your `yarn.lock` will pin specific versions. You *could* enable lock file maintenance but I would instead recommend you start pinning your devDependencies so you can *see* when they are updated in `package.json` instead of having them buried in a `yarn.lock`.

**Comment by charlike** [comment]
in parse-function, hela-preset-tunnckocore should be updated? there the config is renovate-config-tunnckocore (sorry dont have repo for iyt, check the contents of the npm package with that name) which uses mostly the renovate's default :base preset.

in hela, hela-preset-tunnckocore should be updated?

in get-installed-path, hela-preset-tunnckocore should be updated? or at least, if not that, the it should send pr to unpin the global-modules, cuz it is pinned currently (cuz before some weeks I wanted all deps to be pinned)

**Comment by rarkins** [comment]
@charlike I've already given a very in-depth analysis above for `parse-function`. please read it in detail and if you still think something is wrong with it or another repo, please give very specific links to sources including line numbers.

**Comment by charlike** [comment]
yeah I understand, so as I thought it wont send pr if dep is in range - okey, im okey with that and want it that way :)

im more surprised why it not unpin the global-modules then?

as about the advice to pin dev deps... okey, thanks

as about the redundant pinversions, yea accident.

ok, I think we are good and clarified the things :)

ps: sorry im typing from phone

**Comment by rarkins** [comment]
> in get-installed-path, hela-preset-tunnckocore should be updated?

No, because the latest release is within the existing semver range.

> or at least, if not that, the it should send pr to unpin the global-modules

renovate never "unpins", if you've pinned it manually or through config then you need to unpin it.

> cuz it is pinned currently (cuz before some weeks I wanted all deps to be pinned)

No it's not: https://github.com/tunnckoCore/get-installed-path/blob/master/package.json#L34

**Comment by rarkins** [comment]
On pinning/unpinning, Renovate never "unpins". i.e. if user has configured a specific version but then has a config to preserve ranges for `dependencies`, we won't go and add a `^` or `~` to it. Potentially, someone might "accidentally" allow Renovate to pin ranges and then regret it later.. but if they switch config around then we won't attempt to unpin.

**Comment by rarkins** [comment]
If you want any config help to get things running as you wish, could you open the first issue in https://github.com/renovateapp/config-help/issues ? I created it yesterday so people will hopefully feel free to ask config help there if they don't want to pollute this main repo. I see people making some pretty creative configs but rarely asking for help or review.

**Comment by charlike** [comment]
> No it's not

meant that for the global-modules.

> renovate never "unpins", if you've pinned it manually or through config then you need to unpin it.

thought it does that because when pinversions is on and you add dep with range (the default behavior of npm5 and yarn) it sends pr to pin that dependency. but anyway, all is right.

as about pinning vs not pinning deps, I still cant consider. I read your article in the site but didnt help me a lot.

isnt logical to pin all kind of deps when u use lockfiles? because lockfiles are for that - ensure always versions are the same.

**Comment by rarkins** [comment]
> thought it does that because when pinversions is on and you add dep with range (the default behavior of npm5 and yarn) it sends pr to pin that dependency. but anyway, all is right.

Yes, it pins.. it just never "unpins" because it assumes it's pinned for a reason.

> isnt logical to pin all kind of deps when u use lockfiles? because lockfiles are for that - ensure always versions are the same.

lock files only serve to pin within the project (i.e. within developers). If you publish packages/libraries then the lock file is completely ignored and downstream packages will just look at what's in `package.json`. So pinning in `package.json` is preserved downstream while lock files are not.

My approach: always pin, but if you are publishing a browser library then don't pin `dependencies`.

**Comment by charlike** [comment]
haha, the only thing that I understood is the if u pin all kind of deps, than users of such package may get more bigger node_modules folder, because multiple versions may be installed - okey but it gives u guarants for very small cost (if ur pkgs dont have many deps)

**Comment by rarkins** [comment]
> users of such package may get more bigger node_modules folder, because multiple versions may be installed

Right. Which in the browser is usually a bad thing. For node.js, I think it rarely matters that much, not too many dependencies are so large that people will notice.

**Comment by charlike** [comment]
>  it just never "unpins" because it assumes it's pinned for a reason.

cool, good decision.

okey, thanks :) it's awesome that u are almost always here and anyone can get help or clarify things very fast.
