### ISSUE TITLE
Gitlab v4 API 'unable to detect package files' in large repos

### ISSUE THREAD

**Issue by Autre31415** [singapore/renovate#968]
If you have a large repository using a recent version of Gitlab with the v4 API it's possible that package files will go undetected, which will prevent Renovate from working. 

This is due to this API call in `getFileList`:

```
const res = await get(
  `projects/${config.repoName}/repository/tree?ref=${branchName}&recursive=true`
);
```

A recursive list of directories and files is no problem for v3 of the API, as that call will return all of them. But in v4 of the API the results will be returned in pages, with the default amount per page being 20, with a cap of 100 using `&per_page=100` in the URL. This is documented in [this issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/35257#note_35376602).

If you happen to have a large repository with many files/directories your package files can easily go undetected because of this.

**Comment by rarkins** [comment]
Thanks for the clarification. This was raised in #962 today too, but I didn't realise it was specific to APIv4. I will port the API pagination from GitHub over shortly.

**Comment by rarkins** [comment]
Please try version 9.85.1 and confirm if now working or reopen if not, thanks.
