### ISSUE TITLE
labels not being applied to new merge requests in gitlab APIv4

### ISSUE THREAD

**Issue by Autre31415** [singapore/renovate#985]
I suspect the reason for this lies in this API documentation: https://docs.gitlab.com/ee/api/merge_requests.html#update-mr

The v4 API has a tendency to utilize `iid` rather than `id` for referencing merge requests.

**Comment by rarkins** [comment]
Thank you for the bug report. GitLab have been killing me with all these API changes!

The signature for `addLabels` is:
```
async function addLabels(prNo, labels) {
```

and in the code (common for GitHub and GitLab) we pass it `pr.prNo` which comes from `id`, not `iid`:   `pr.number = pr.id;`

If GitLab have moved to using `id` instead of `iid` for *everything* then we can essentially just ignore `id`. But I suspect they might still have some inconsistencies.

In that case, we may need to refactor the API signatures for PR-functions at least so that `addLabels` and perhaps others accept the full `pr` object as parameter instead of `prNo`. That way GitHub API can then use `pr.number` while GitLab can use `pr.iid`.

**Comment by rarkins** [comment]
Another alternative is to apply labels as part of PR creation, because that's the only time we add labels (currently). GitLab supports this in the same request but GitHub does not, but it could be added as a 2-step API call in GitHub.

**Comment by dherges** [comment]
They have also changed something in GitLab 10 which causes updating an existing breanch to fail ...


```
 INFO: Branch has 1 upgrade(s) (repository=184, dependencies=rxjs, branch=renovate/rxjs-5.x)
 INFO: Branch needs creating (repository=184, dependencies=rxjs, branch=renovate/rxjs-5.x)
 INFO: Generated lockfile (repository=184, dependencies=rxjs, branch=renovate/rxjs-5.x)
       "durationSeconds": 69,
       "lockFile": "yarn.lock"
ERROR: Error updating branch: Branch already exists (400) (repository=184, dependencies=rxjs, branch=renovate/rxjs-5.x)
       "err": {
         "name": "GitLabError",
```

**Comment by rarkins** [comment]
@dherges can you check it's not the same cause as described in https://github.com/singapore/renovate/issues/829#issuecomment-336912956 ?

i.e. GitLab have made encoding forward slashes mandatory but some people are using reverse proxies in front of their API that *decode* escaped strings before passing it to GitLab, causing requests to fail

Otherwise it seems like something wrong with `branchExists()`

**Comment by dherges** [comment]
This is why we put the project id (rather than the repository ids) in the config (e.g. `184` instead of `my-group/my-project`). Nut we have also upgraded from 9.3 to 10.x. Will need to investigate further / later.

**Comment by Autre31415** [comment]
I had to use the project ID as well in the past and didn't fully understood why I needed to at the time. Once 9.5 hit and encoded slashes became necessary in branch names that's when I went on to discover the need to ensure that they are not being decoded. You can demonstrate the issue in your browser by manually navigating to the branch URL: `yourGitlab.com/api/v4/projects/projectName/repository/branches/branchName`

If you manually encode the slash in the branchname by replacing it with `%2F` you can see how the server responds. In my case I would got a generic 404 error page from the rather than a JSON response from the API.

How to alter this behavior depends on what web server you're using to host gitlab, and if any other servers are in the stack as well.

If nginx: Ensure that the URI is being passed in unprocessed form by eliminating the trailing `/` in the `proxy_pass` configuration. 

Example:

Use  `proxy_pass http://example.gitlab;` over `proxy_pass http://example.gitlab/;`

If Apache:

Ensure the `AllowEncodedSlashes NoDecode` option is used.

If Apache is set to ProxyPass to nginx: Append `nocanon` to the route. i.e.: `ProxyPass / http://localhost:port/ nocanon`

A workaround for this in the meantime is to point renovate at the v3 API which doesn't require the branch name slash to be encoded.

**Comment by dherges** [comment]
api/v4/projects/184/repository/branches/renovate%2Fbootstrap-4.x
`{"error":"404 Not Found"}`

api/v4/projects/184/repository/branches/renovate/bootstrap-4.x
`{"error":"404 Not Found"}`

api/v4/projects/184
`{"id":184, ... }` 

Neither does respond ... I don't know why.

**Comment by rarkins** [comment]
@dherges if a reverse proxy converts %2F to / then that would explain it. Ie in both cases GitLab sees / not %2F

**Comment by dherges** [comment]
Yes there is a rev proxy in front ... 

Cheers, David

**Comment by Autre31415** [comment]
The fact you're getting a generic 404 JSON response does indeed indicate that the `/` is being decoded. It's causing you to go to a deeper undefined route. Under normal conditions if you were to try and navigate to a branch that doesn't exist, or spell a branch name wrong, etc you'd get a more descriptive error like this:
```
{
"message": "404 Branch Not Found"
}
```

You could demonstrate that by removing the `/` in the URL which would of course leave you with a branch name that doesn't exist and the error will change, but toss that `/` anywhere in your branch name and the error changes back to the generic 404.

**Comment by rarkins** [comment]
FYI I am working on a new api v4-only PR here: https://github.com/singapore/renovate/pull/1064
